wordsApp.constant("letters", [
	{name:          'A',
 	 blockImg:      'common/images/letters/blocks/A.png',
 	 lettersImg:    'common/images/letters/Aa.png',
 	 eng_name:      'common/audio/letters/eng/a.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/ap.mp3',
 	 por_name:      'common/audio/letters/por/a.mp3',
 	 por_pronounce: 'common/audio/letters/por/ap.mp3',
 	 esp_name:      'common/audio/letters/esp/a.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/ap.mp3'
 	},
	{name:          'B',
 	 blockImg:      'common/images/letters/blocks/B.png',
 	 lettersImg:    'common/images/letters/Bb.png',
 	 eng_name:      'common/audio/letters/eng/b.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/bp.mp3',
 	 por_name:      'common/audio/letters/por/b.mp3',
 	 por_pronounce: 'common/audio/letters/por/bp.mp3',
 	 esp_name:      'common/audio/letters/esp/b.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/bp.mp3'
 	},
	{name:          'C',
 	 blockImg:      'common/images/letters/blocks/C.png',
 	 lettersImg:    'common/images/letters/Cc.png',
 	 eng_name:      'common/audio/letters/eng/c.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/cp.mp3',
 	 por_name:      'common/audio/letters/por/c.mp3',
 	 por_pronounce: 'common/audio/letters/por/cp.mp3',
 	 esp_name:      'common/audio/letters/esp/c.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/cp.mp3'
 	},
	{name:          'D',
 	 blockImg:      'common/images/letters/blocks/D.png',
 	 lettersImg:    'common/images/letters/Dd.png',
 	 eng_name:      'common/audio/letters/eng/d.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/dp.mp3',
 	 por_name:      'common/audio/letters/por/d.mp3',
 	 por_pronounce: 'common/audio/letters/por/dp.mp3',
 	 esp_name:      'common/audio/letters/esp/d.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/dp.mp3'
 	},
	{name:          'E',
 	 blockImg:      'common/images/letters/blocks/E.png',
 	 lettersImg:    'common/images/letters/Ee.png',
 	 eng_name:      'common/audio/letters/eng/e.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/ep.mp3',
 	 por_name:      'common/audio/letters/por/e.mp3',
 	 por_pronounce: 'common/audio/letters/por/ep.mp3',
 	 esp_name:      'common/audio/letters/esp/e.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/ep.mp3'
 	},
	{name:          'F',
 	 blockImg:      'common/images/letters/blocks/F.png',
 	 lettersImg:    'common/images/letters/Ff.png',
 	 eng_name:      'common/audio/letters/eng/f.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/fp.mp3',
 	 por_name:      'common/audio/letters/por/f.mp3',
 	 por_pronounce: 'common/audio/letters/por/fp.mp3',
 	 esp_name:      'common/audio/letters/esp/f.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/fp.mp3'
 	},
	{name:          'G',
 	 blockImg:      'common/images/letters/blocks/G.png',
 	 lettersImg:    'common/images/letters/Gg.png',
 	 eng_name:      'common/audio/letters/eng/g.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/gp.mp3',
 	 por_name:      'common/audio/letters/por/g.mp3',
 	 por_pronounce: 'common/audio/letters/por/gp.mp3',
 	 esp_name:      'common/audio/letters/esp/g.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/gp.mp3'
 	},
	{name:          'H',
 	 blockImg:      'common/images/letters/blocks/H.png',
 	 lettersImg:    'common/images/letters/Hh.png',
 	 eng_name:      'common/audio/letters/eng/h.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/hp.mp3',
 	 por_name:      'common/audio/letters/por/h.mp3',
 	 por_pronounce: 'common/audio/letters/por/hp.mp3',
 	 esp_name:      'common/audio/letters/esp/h.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/hp.mp3'
 	},
	{name:          'I',
 	 blockImg:      'common/images/letters/blocks/I.png',
 	 lettersImg:    'common/images/letters/Ii.png',
 	 eng_name:      'common/audio/letters/eng/i.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/ip.mp3',
 	 por_name:      'common/audio/letters/por/i.mp3',
 	 por_pronounce: 'common/audio/letters/por/ip.mp3',
 	 esp_name:      'common/audio/letters/esp/i.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/ip.mp3'
 	},
	{name:          'J',
 	 blockImg:      'common/images/letters/blocks/J.png',
 	 lettersImg:    'common/images/letters/Jj.png',
 	 eng_name:      'common/audio/letters/eng/j.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/jp.mp3',
 	 por_name:      'common/audio/letters/por/j.mp3',
 	 por_pronounce: 'common/audio/letters/por/jp.mp3',
 	 esp_name:      'common/audio/letters/esp/j.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/jp.mp3'
 	},
	{name:          'K',
 	 blockImg:      'common/images/letters/blocks/K.png',
 	 lettersImg:    'common/images/letters/Kk.png',
 	 eng_name:      'common/audio/letters/eng/k.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/kp.mp3',
 	 por_name:      'common/audio/letters/por/k.mp3',
 	 por_pronounce: 'common/audio/letters/por/kp.mp3',
 	 esp_name:      'common/audio/letters/esp/k.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/kp.mp3'
 	},
	{name:          'L',
 	 blockImg:      'common/images/letters/blocks/L.png',
 	 lettersImg:    'common/images/letters/Ll.png',
 	 eng_name:      'common/audio/letters/eng/l.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/lp.mp3',
 	 por_name:      'common/audio/letters/por/l.mp3',
 	 por_pronounce: 'common/audio/letters/por/lp.mp3',
 	 esp_name:      'common/audio/letters/esp/l.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/lp.mp3'
 	},
	{name:          'M',
 	 blockImg:      'common/images/letters/blocks/M.png',
 	 lettersImg:    'common/images/letters/Mm.png',
 	 eng_name:      'common/audio/letters/eng/m.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/mp.mp3',
 	 por_name:      'common/audio/letters/por/m.mp3',
 	 por_pronounce: 'common/audio/letters/por/mp.mp3',
 	 esp_name:      'common/audio/letters/esp/m.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/mp.mp3'
 	},
	{name:          'N',
 	 blockImg:      'common/images/letters/blocks/N.png',
 	 lettersImg:    'common/images/letters/Nn.png',
 	 eng_name:      'common/audio/letters/eng/n.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/np.mp3',
 	 por_name:      'common/audio/letters/por/n.mp3',
 	 por_pronounce: 'common/audio/letters/por/np.mp3',
 	 esp_name:      'common/audio/letters/esp/n.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/np.mp3'
 	},
	{name:          'O',
 	 blockImg:      'common/images/letters/blocks/O.png',
 	 lettersImg:    'common/images/letters/Oo.png',
 	 eng_name:      'common/audio/letters/eng/o.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/op.mp3',
 	 por_name:      'common/audio/letters/por/o.mp3',
 	 por_pronounce: 'common/audio/letters/por/op.mp3',
 	 esp_name:      'common/audio/letters/esp/o.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/op.mp3'
 	},
	{name:          'P',
 	 blockImg:      'common/images/letters/blocks/P.png',
 	 lettersImg:    'common/images/letters/Pp.png',
 	 eng_name:      'common/audio/letters/eng/p.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/pp.mp3',
 	 por_name:      'common/audio/letters/por/p.mp3',
 	 por_pronounce: 'common/audio/letters/por/pp.mp3',
 	 esp_name:      'common/audio/letters/esp/p.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/pp.mp3'
 	},
	{name:          'Q',
 	 blockImg:      'common/images/letters/blocks/Q.png',
 	 lettersImg:    'common/images/letters/Qq.png',
 	 eng_name:      'common/audio/letters/eng/q.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/qp.mp3',
 	 por_name:      'common/audio/letters/por/q.mp3',
 	 por_pronounce: 'common/audio/letters/por/qp.mp3',
 	 esp_name:      'common/audio/letters/esp/q.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/qp.mp3'
 	},
	{name:          'R',
 	 blockImg:      'common/images/letters/blocks/R.png',
 	 lettersImg:    'common/images/letters/Rr.png',
 	 eng_name:      'common/audio/letters/eng/r.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/rp.mp3',
 	 por_name:      'common/audio/letters/por/r.mp3',
 	 por_pronounce: 'common/audio/letters/por/rp.mp3',
 	 esp_name:      'common/audio/letters/esp/r.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/rp.mp3'
 	},
	{name:          'S',
 	 blockImg:      'common/images/letters/blocks/S.png',
 	 lettersImg:    'common/images/letters/Ss.png',
 	 eng_name:      'common/audio/letters/eng/s.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/sp.mp3',
 	 por_name:      'common/audio/letters/por/s.mp3',
 	 por_pronounce: 'common/audio/letters/por/sp.mp3',
 	 esp_name:      'common/audio/letters/esp/s.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/sp.mp3'
 	},
	{name:          'T',
 	 blockImg:      'common/images/letters/blocks/T.png',
 	 lettersImg:    'common/images/letters/Tt.png',
 	 eng_name:      'common/audio/letters/eng/t.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/tp.mp3',
 	 por_name:      'common/audio/letters/por/t.mp3',
 	 por_pronounce: 'common/audio/letters/por/tp.mp3',
 	 esp_name:      'common/audio/letters/esp/t.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/tp.mp3'
 	},
	{name:          'U',
 	 blockImg:      'common/images/letters/blocks/U.png',
 	 lettersImg:    'common/images/letters/Uu.png',
 	 eng_name:      'common/audio/letters/eng/u.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/up.mp3',
 	 por_name:      'common/audio/letters/por/u.mp3',
 	 por_pronounce: 'common/audio/letters/por/up.mp3',
 	 esp_name:      'common/audio/letters/esp/u.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/up.mp3'
 	},
	{name:          'V',
 	 blockImg:      'common/images/letters/blocks/V.png',
 	 lettersImg:    'common/images/letters/Vv.png',
 	 eng_name:      'common/audio/letters/eng/v.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/vp.mp3',
 	 por_name:      'common/audio/letters/por/v.mp3',
 	 por_pronounce: 'common/audio/letters/por/vp.mp3',
 	 esp_name:      'common/audio/letters/esp/v.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/vp.mp3'
 	},
	{name:          'W',
 	 blockImg:      'common/images/letters/blocks/W.png',
 	 lettersImg:    'common/images/letters/Ww.png',
 	 eng_name:      'common/audio/letters/eng/w.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/wp.mp3',
 	 por_name:      'common/audio/letters/por/w.mp3',
 	 por_pronounce: 'common/audio/letters/por/wp.mp3',
 	 esp_name:      'common/audio/letters/esp/w.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/wp.mp3'
 	},
	{name:          'X',
 	 blockImg:      'common/images/letters/blocks/X.png',
 	 lettersImg:    'common/images/letters/Xx.png',
 	 eng_name:      'common/audio/letters/eng/x.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/xp.mp3',
 	 por_name:      'common/audio/letters/por/x.mp3',
 	 por_pronounce: 'common/audio/letters/por/xp.mp3',
 	 esp_name:      'common/audio/letters/esp/x.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/xp.mp3'
 	},
	{name:          'Y',
 	 blockImg:      'common/images/letters/blocks/Y.png',
 	 lettersImg:    'common/images/letters/Yy.png',
 	 eng_name:      'common/audio/letters/eng/y.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/yp.mp3',
 	 por_name:      'common/audio/letters/por/y.mp3',
 	 por_pronounce: 'common/audio/letters/por/yp.mp3',
 	 esp_name:      'common/audio/letters/esp/y.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/yp.mp3'
 	},
	{name:          'Z',
 	 blockImg:      'common/images/letters/blocks/Z.png',
 	 lettersImg:    'common/images/letters/Zz.png',
 	 eng_name:      'common/audio/letters/eng/z.mp3',
 	 eng_pronounce: 'common/audio/letters/eng/zp.mp3',
 	 por_name:      'common/audio/letters/por/z.mp3',
 	 por_pronounce: 'common/audio/letters/por/zp.mp3',
 	 esp_name:      'common/audio/letters/esp/z.mp3',
 	 esp_pronounce: 'common/audio/letters/esp/zp.mp3'
 	}
]);