wordsApp.constant("words", [
	{id:        0,
	 Eng_name:  'Apple',
	 Eng_audio: 'common/audio/words/eng/0.mp3',
	 Por_name:  'Maçã',
	 Por_audio: 'common/audio/words/por/0.mp3',
	 Esp_name:  'Manzana',
	 Esp_audio: 'common/audio/words/esp/0.mp3',
 	 img: 'common/images/words/0.png'
 	},
	{id:        1,
	 Eng_name:  'Apron',
	 Eng_audio: 'common/audio/words/eng/1.mp3',
	 Por_name:  'Avental',
	 Por_audio: 'common/audio/words/por/1.mp3',
	 Esp_name:  'Delantal',
	 Esp_audio: 'common/audio/words/esp/1.mp3',
 	 img:       'common/images/words/1.png'
 	},
	{id:        2,
	 Eng_name:  'Ant',
	 Eng_audio: 'common/audio/words/eng/2.mp3',
	 Por_name:  'Formiga',
	 Por_audio: 'common/audio/words/por/2.mp3',
	 Esp_name:  'Hormiga',
	 Esp_audio: 'common/audio/words/esp/2.mp3',
 	 img:       'common/images/words/2.png'
 	},
	{id:        3,
	 Eng_name:  'Anchor',
	 Eng_audio: 'common/audio/words/eng/3.mp3',
	 Por_name:  'Âncora',
	 Por_audio: 'common/audio/words/por/3.mp3',
	 Esp_name:  'Ancla',
	 Esp_audio: 'common/audio/words/esp/3.mp3',
 	 img:       'common/images/words/3.png'
 	},
	{id:        4,
	 Eng_name:  'Acorn',
	 Eng_audio: 'common/audio/words/eng/4.mp3',
	 Por_name:  'Bolota',
	 Por_audio: 'common/audio/words/por/4.mp3',
	 Esp_name:  'Bellota',
	 Esp_audio: 'common/audio/words/esp/4.mp3',
 	 img:       'common/images/words/4.png'
 	},
	{id:        5,
	 Eng_name:  'Alligator',
	 Eng_audio: 'common/audio/words/eng/5.mp3',
	 Por_name:  'Jacaré',
	 Por_audio: 'common/audio/words/por/5.mp3',
	 Esp_name:  'Caimán',
	 Esp_audio: 'common/audio/words/esp/5.mp3',
 	 img:       'common/images/words/5.png'
 	},
	{id:        6,
	 Eng_name:  'Armadilo',
	 Eng_audio: 'common/audio/words/eng/6.mp3',
	 Por_name:  'Tatu',
	 Por_audio: 'common/audio/words/por/6.mp3',
	 Esp_name:  'Armadillo',
	 Esp_audio: 'common/audio/words/esp/6.mp3',
 	 img:       'common/images/words/6.png'
 	},
	{id:        7,
	 Eng_name:  'Brocolli',
	 Eng_audio: 'common/audio/words/eng/7.mp3',
	 Por_name:  'Brócolis',
	 Por_audio: 'common/audio/words/por/7.mp3',
	 Esp_name:  'Brócoli',
	 Esp_audio: 'common/audio/words/esp/7.mp3',
 	 img:       'common/images/words/7.png'
 	},
	{id:        8,
	 Eng_name:  'Butterfly',
	 Eng_audio: 'common/audio/words/eng/8.mp3',
	 Por_name:  'Borboleta',
	 Por_audio: 'common/audio/words/por/8.mp3',
	 Esp_name:  'Mariposa',
	 Esp_audio: 'common/audio/words/esp/8.mp3',
 	 img:       'common/images/words/8.png'
 	},
	{id:        9,
	 Eng_name:  'Beaver',
	 Eng_audio: 'common/audio/words/eng/9.mp3',
	 Por_name:  'Castor',
	 Por_audio: 'common/audio/words/por/9.mp3',
	 Esp_name:  'Castor',
	 Esp_audio: 'common/audio/words/esp/9.mp3',
 	 img:       'common/images/words/9.png'
 	},
	{id:        10,
	 Eng_name:  'Bear',
	 Eng_audio: 'common/audio/words/eng/10.mp3',
	 Por_name:  'Urso',
	 Por_audio: 'common/audio/words/por/10.mp3',
	 Esp_name:  'Oso',
	 Esp_audio: 'common/audio/words/esp/10.mp3',
 	 img:       'common/images/words/10.png'
 	},
	{id:        11,
	 Eng_name:  'Bat',
	 Eng_audio: 'common/audio/words/eng/11.mp3',
	 Por_name:  'Morcego',
	 Por_audio: 'common/audio/words/por/11.mp3',
	 Esp_name:  'Murciélago',
	 Esp_audio: 'common/audio/words/esp/11.mp3',
 	 img:       'common/images/words/11.png'
 	},
	{id:        12,
	 Eng_name:  'Books',
	 Eng_audio: 'common/audio/words/eng/12.mp3',
	 Por_name:  'Livros',
	 Por_audio: 'common/audio/words/por/12.mp3',
	 Esp_name:  'Libros',
	 Esp_audio: 'common/audio/words/esp/12.mp3',
 	 img:       'common/images/words/12.png'
 	},
	{id:        13,
	 Eng_name:  'Balloon',
	 Eng_audio: 'common/audio/words/eng/13.mp3',
	 Por_name:  'Balão',
	 Por_audio: 'common/audio/words/por/13.mp3',
	 Esp_name:  'Globo',
	 Esp_audio: 'common/audio/words/esp/13.mp3',
 	 img:       'common/images/words/13.png'
 	},
	{id:        14,
	 Eng_name:  'Ball',
	 Eng_audio: 'common/audio/words/eng/14.mp3',
	 Por_name:  'Bola',
	 Por_audio: 'common/audio/words/por/14.mp3',
	 Esp_name:  'Pelota',
	 Esp_audio: 'common/audio/words/esp/14.mp3',
 	 img:       'common/images/words/14.png'
 	},
	{id:        15,
	 Eng_name:  'Bee',
	 Eng_audio: 'common/audio/words/eng/15.mp3',
	 Por_name:  'Abelha',
	 Por_audio: 'common/audio/words/por/15.mp3',
	 Esp_name:  'Abeja',
	 Esp_audio: 'common/audio/words/esp/15.mp3',
 	 img:       'common/images/words/15.png'
 	},
	{id:        16,
	 Eng_name:  'Bananas',
	 Eng_audio: 'common/audio/words/eng/16.mp3',
	 Por_name:  'Bananas',
	 Por_audio: 'common/audio/words/por/16.mp3',
	 Esp_name:  'Plátanos',
	 Esp_audio: 'common/audio/words/esp/16.mp3',
 	 img:       'common/images/words/16.png'
 	},
	{id:        17,
	 Eng_name:  'Cricket',
	 Eng_audio: 'common/audio/words/eng/17.mp3',
	 Por_name:  'Grilo',
	 Por_audio: 'common/audio/words/por/17.mp3',
	 Esp_name:  'Grillo',
	 Esp_audio: 'common/audio/words/esp/17.mp3',
 	 img:       'common/images/words/17.png'
 	},
	{id:        18,
	 Eng_name:  'Chicken',
	 Eng_audio: 'common/audio/words/eng/18.mp3',
	 Por_name:  'Galinha',
	 Por_audio: 'common/audio/words/por/18.mp3',
	 Esp_name:  'Pollo',
	 Esp_audio: 'common/audio/words/esp/18.mp3',
 	 img:       'common/images/words/18.png'
 	},
	{id:        19,
	 Eng_name:  'Cat',
	 Eng_audio: 'common/audio/words/eng/19.mp3',
	 Por_name:  'Gato',
	 Por_audio: 'common/audio/words/por/19.mp3',
	 Esp_name:  'Gato',
	 Esp_audio: 'common/audio/words/esp/19.mp3',
 	 img:       'common/images/words/19.png'
 	},
	{id:        20,
	 Eng_name:  'Cake',
	 Eng_audio: 'common/audio/words/eng/20.mp3',
	 Por_name:  'Bolo',
	 Por_audio: 'common/audio/words/por/20.mp3',
	 Esp_name:  'Pastel',
	 Esp_audio: 'common/audio/words/esp/20.mp3',
 	 img:       'common/images/words/20.png'
 	},
	{id:        21,
	 Eng_name:  'Crayon',
	 Eng_audio: 'common/audio/words/eng/21.mp3',
	 Por_name:  'Giz de cera',
	 Por_audio: 'common/audio/words/por/21.mp3',
	 Esp_name:  'lápiz de color',
	 Esp_audio: 'common/audio/words/esp/21.mp3',
 	 img:       'common/images/words/21.png'
 	},
	{id:        22,
	 Eng_name:  'Cherries',
	 Eng_audio: 'common/audio/words/eng/22.mp3',
	 Por_name:  'Cerejas',
	 Por_audio: 'common/audio/words/por/22.mp3',
	 Esp_name:  'Cerezas',
	 Esp_audio: 'common/audio/words/esp/22.mp3',
 	 img:       'common/images/words/22.png'
 	},
	{id:        23,
	 Eng_name:  'Cow',
	 Eng_audio: 'common/audio/words/eng/23.mp3',
	 Por_name:  'Vaca',
	 Por_audio: 'common/audio/words/por/23.mp3',
	 Esp_name:  'Vaca',
	 Esp_audio: 'common/audio/words/esp/23.mp3',
 	 img:       'common/images/words/23.png'
 	},
	{id:        24,
	 Eng_name:  'Cheese',
	 Eng_audio: 'common/audio/words/eng/24.mp3',
	 Por_name:  'Queijo',
	 Por_audio: 'common/audio/words/por/24.mp3',
	 Esp_name:  'Queso',
	 Esp_audio: 'common/audio/words/esp/24.mp3',
 	 img:       'common/images/words/24.png'
 	},
	{id:        25,
	 Eng_name:  'Car',
	 Eng_audio: 'common/audio/words/eng/25.mp3',
	 Por_name:  'Carro',
	 Por_audio: 'common/audio/words/por/25.mp3',
	 Esp_name:  'Coche',
	 Esp_audio: 'common/audio/words/esp/25.mp3',
 	 img:       'common/images/words/25.png'
 	},
	{id:        26,
	 Eng_name:  'Dinosaur',
	 Eng_audio: 'common/audio/words/eng/26.mp3',
	 Por_name:  'Dinossauro',
	 Por_audio: 'common/audio/words/por/26.mp3',
	 Esp_name:  'Dinosaurio',
	 Esp_audio: 'common/audio/words/esp/26.mp3',
 	 img:       'common/images/words/26.png'
 	},
	{id:        27,
	 Eng_name:  'Dice',
	 Eng_audio: 'common/audio/words/eng/27.mp3',
	 Por_name:  'Dados',
	 Por_audio: 'common/audio/words/por/27.mp3',
	 Esp_name:  'Dados',
	 Esp_audio: 'common/audio/words/esp/27.mp3',
 	 img:       'common/images/words/27.png'
 	},
	{id:        28,
	 Eng_name:  'Drill',
	 Eng_audio: 'common/audio/words/eng/28.mp3',
	 Por_name:  'Furadeira',
	 Por_audio: 'common/audio/words/por/28.mp3',
	 Esp_name:  'Taladro',
	 Esp_audio: 'common/audio/words/esp/28.mp3',
 	 img:       'common/images/words/28.png'
 	},
	{id:        29,
	 Eng_name:  'Duck',
	 Eng_audio: 'common/audio/words/eng/29.mp3',
	 Por_name:  'Pato',
	 Por_audio: 'common/audio/words/por/29.mp3',
	 Esp_name:  'Pato',
	 Esp_audio: 'common/audio/words/esp/29.mp3',
 	 img:       'common/images/words/29.png'
 	},
	{id:        30,
	 Eng_name:  'Door',
	 Eng_audio: 'common/audio/words/eng/30.mp3',
	 Por_name:  'Porta',
	 Por_audio: 'common/audio/words/por/30.mp3',
	 Esp_name:  'Puerta',
	 Esp_audio: 'common/audio/words/esp/30.mp3',
 	 img:       'common/images/words/30.png'
 	},
	{id:        31,
	 Eng_name:  'Drum',
	 Eng_audio: 'common/audio/words/eng/31.mp3',
	 Por_name:  'Tambor',
	 Por_audio: 'common/audio/words/por/31.mp3',
	 Esp_name:  'Tambor',
	 Esp_audio: 'common/audio/words/esp/31.mp3',
 	 img:       'common/images/words/31.png'
 	},
	{id:        32,
	 Eng_name:  'Dolphin',
	 Eng_audio: 'common/audio/words/eng/32.mp3',
	 Por_name:  'Golfinho',
	 Por_audio: 'common/audio/words/por/32.mp3',
	 Esp_name:  'Delfín',
	 Esp_audio: 'common/audio/words/esp/32.mp3',
 	 img:       'common/images/words/32.png'
 	},
	{id:        33,
	 Eng_name:  'Dog',
	 Eng_audio: 'common/audio/words/eng/33.mp3',
	 Por_name:  'Cachorro',
	 Por_audio: 'common/audio/words/por/33.mp3',
	 Esp_name:  'Perro',
	 Esp_audio: 'common/audio/words/esp/33.mp3',
 	 img:       'common/images/words/33.png'
 	},
	{id:        34,
	 Eng_name:  'Elephant',
	 Eng_audio: 'common/audio/words/eng/34.mp3',
	 Por_name:  'Elefante',
	 Por_audio: 'common/audio/words/por/34.mp3',
	 Esp_name:  'Elefante',
	 Esp_audio: 'common/audio/words/esp/34.mp3',
 	 img:       'common/images/words/34.png'
 	},
	{id:        35,
	 Eng_name:  'Earth',
	 Eng_audio: 'common/audio/words/eng/35.mp3',
	 Por_name:  'Terra',
	 Por_audio: 'common/audio/words/por/35.mp3',
	 Esp_name:  'Tierra',
	 Esp_audio: 'common/audio/words/esp/35.mp3',
 	 img:       'common/images/words/35.png'
 	},
	{id:        36,
	 Eng_name:  'Eggs',
	 Eng_audio: 'common/audio/words/eng/36.mp3',
	 Por_name:  'Ovos',
	 Por_audio: 'common/audio/words/por/36.mp3',
	 Esp_name:  'Huevos',
	 Esp_audio: 'common/audio/words/esp/36.mp3',
 	 img:       'common/images/words/36.png'
 	},
	{id:        37,
	 Eng_name:  'Flowers',
	 Eng_audio: 'common/audio/words/eng/37.mp3',
	 Por_name:  'Flores',
	 Por_audio: 'common/audio/words/por/37.mp3',
	 Esp_name:  'Flores',
	 Esp_audio: 'common/audio/words/esp/37.mp3',
 	 img:       'common/images/words/37.png'
 	},
	{id:        38,
	 Eng_name:  'Frog',
	 Eng_audio: 'common/audio/words/eng/38.mp3',
	 Por_name:  'Sapo',
	 Por_audio: 'common/audio/words/por/38.mp3',
	 Esp_name:  'Rana',
	 Esp_audio: 'common/audio/words/esp/38.mp3',
 	 img:       'common/images/words/38.png'
 	},
	{id:        39,
	 Eng_name:  'Fish',
	 Eng_audio: 'common/audio/words/eng/39.mp3',
	 Por_name:  'Peixe',
	 Por_audio: 'common/audio/words/por/39.mp3',
	 Esp_name:  'Pescado',
	 Esp_audio: 'common/audio/words/esp/39.mp3',
 	 img:       'common/images/words/39.png'
 	},
	{id:        40,
	 Eng_name:  'Guitar',
	 Eng_audio: 'common/audio/words/eng/40.mp3',
	 Por_name:  'Guitarra',
	 Por_audio: 'common/audio/words/por/40.mp3',
	 Esp_name:  'Guitarra',
	 Esp_audio: 'common/audio/words/esp/40.mp3',
 	 img:       'common/images/words/40.png'
 	},
	{id:        41,
	 Eng_name:  'Goose',
	 Eng_audio: 'common/audio/words/eng/41.mp3',
	 Por_name:  'Ganso',
	 Por_audio: 'common/audio/words/por/41.mp3',
	 Esp_name:  'Ganso',
	 Esp_audio: 'common/audio/words/esp/41.mp3',
 	 img:       'common/images/words/41.png'
 	},
	{id:        42,
	 Eng_name:  'Garden',
	 Eng_audio: 'common/audio/words/eng/42.mp3',
	 Por_name:  'Jardim',
	 Por_audio: 'common/audio/words/por/42.mp3',
	 Esp_name:  'Jardín',
	 Esp_audio: 'common/audio/words/esp/42.mp3',
 	 img:       'common/images/words/42.png'
 	},
	{id:        43,
	 Eng_name:  'Giraffe',
	 Eng_audio: 'common/audio/words/eng/43.mp3',
	 Por_name:  'Girafa',
	 Por_audio: 'common/audio/words/por/43.mp3',
	 Esp_name:  'Jirafa',
	 Esp_audio: 'common/audio/words/esp/43.mp3',
 	 img:       'common/images/words/43.png'
 	},
	{id:        44,
	 Eng_name:  'Goat',
	 Eng_audio: 'common/audio/words/eng/44.mp3',
	 Por_name:  'Bode',
	 Por_audio: 'common/audio/words/por/44.mp3',
	 Esp_name:  'Cabra',
	 Esp_audio: 'common/audio/words/esp/44.mp3',
 	 img:       'common/images/words/44.png'
 	},
	{id:        45,
	 Eng_name:  'Grapes',
	 Eng_audio: 'common/audio/words/eng/45.mp3',
	 Por_name:  'Uvas',
	 Por_audio: 'common/audio/words/por/45.mp3',
	 Esp_name:  'Uvas',
	 Esp_audio: 'common/audio/words/esp/45.mp3',
 	 img:       'common/images/words/45.png'
 	},
	{id:        46,
	 Eng_name:  'Grasshopper',
	 Eng_audio: 'common/audio/words/eng/46.mp3',
	 Por_name:  'Gafanhoto',
	 Por_audio: 'common/audio/words/por/46.mp3',
	 Esp_name:  'Saltamontes',
	 Esp_audio: 'common/audio/words/esp/46.mp3',
 	 img:       'common/images/words/46.png'
 	},
	{id:        47,
	 Eng_name:  'Gift',
	 Eng_audio: 'common/audio/words/eng/47.mp3',
	 Por_name:  'Presente',
	 Por_audio: 'common/audio/words/por/47.mp3',
	 Esp_name:  'Regalo',
	 Esp_audio: 'common/audio/words/esp/47.mp3',
 	 img:       'common/images/words/47.png'
 	},
	{id:        48,
	 Eng_name:  'Hamster',
	 Eng_audio: 'common/audio/words/eng/48.mp3',
	 Por_name:  'Hámster',
	 Por_audio: 'common/audio/words/por/48.mp3',
	 Esp_name:  'Hámster',
	 Esp_audio: 'common/audio/words/esp/48.mp3',
 	 img:       'common/images/words/48.png'
 	},
	{id:        49,
	 Eng_name:  'Hands',
	 Eng_audio: 'common/audio/words/eng/49.mp3',
	 Por_name:  'Mãos',
	 Por_audio: 'common/audio/words/por/49.mp3',
	 Esp_name:  'Manos',
	 Esp_audio: 'common/audio/words/esp/49.mp3',
 	 img:       'common/images/words/49.png'
 	},
	{id:        50,
	 Eng_name:  'Harp',
	 Eng_audio: 'common/audio/words/eng/50.mp3',
	 Por_name:  'Harpa',
	 Por_audio: 'common/audio/words/por/50.mp3',
	 Esp_name:  'Arpa',
	 Esp_audio: 'common/audio/words/esp/50.mp3',
 	 img:       'common/images/words/50.png'
 	},
	{id:        51,
	 Eng_name:  'Hair',
	 Eng_audio: 'common/audio/words/eng/51.mp3',
	 Por_name:  'Cabelo',
	 Por_audio: 'common/audio/words/por/51.mp3',
	 Esp_name:  'Cabello',
	 Esp_audio: 'common/audio/words/esp/51.mp3',
 	 img:       'common/images/words/51.png'
 	},
	{id:        52,
	 Eng_name:  'Heart',
	 Eng_audio: 'common/audio/words/eng/52.mp3',
	 Por_name:  'Coração',
	 Por_audio: 'common/audio/words/por/52.mp3',
	 Esp_name:  'Corazón',
	 Esp_audio: 'common/audio/words/esp/52.mp3',
 	 img:       'common/images/words/52.png'
 	},
	{id:        53,
	 Eng_name:  'Hay',
	 Eng_audio: 'common/audio/words/eng/53.mp3',
	 Por_name:  'Feno',
	 Por_audio: 'common/audio/words/por/53.mp3',
	 Esp_name:  'Heno',
	 Esp_audio: 'common/audio/words/esp/53.mp3',
 	 img:       'common/images/words/53.png'
 	},
	{id:        54,
	 Eng_name:  'Horse',
	 Eng_audio: 'common/audio/words/eng/54.mp3',
	 Por_name:  'Cavalo',
	 Por_audio: 'common/audio/words/por/54.mp3',
	 Esp_name:  'Caballo',
	 Esp_audio: 'common/audio/words/esp/54.mp3',
 	 img:       'common/images/words/54.png'
 	},
	{id:        55,
	 Eng_name:  'Hot Dog',
	 Eng_audio: 'common/audio/words/eng/55.mp3',
	 Por_name:  'Cachorro Quente',
	 Por_audio: 'common/audio/words/por/55.mp3',
	 Esp_name:  'Perrito Caliente',
	 Esp_audio: 'common/audio/words/esp/55.mp3',
 	 img:       'common/images/words/55.png'
 	},
	{id:        56,
	 Eng_name:  'Hat',
	 Eng_audio: 'common/audio/words/eng/56.mp3',
	 Por_name:  'Chapéu',
	 Por_audio: 'common/audio/words/por/56.mp3',
	 Esp_name:  'Sombrero',
	 Esp_audio: 'common/audio/words/esp/56.mp3',
 	 img:       'common/images/words/56.png'
 	},
	{id:        57,
	 Eng_name:  'Hanger',
	 Eng_audio: 'common/audio/words/eng/57.mp3',
	 Por_name:  'Cabide',
	 Por_audio: 'common/audio/words/por/57.mp3',
	 Esp_name:  'Percha',
	 Esp_audio: 'common/audio/words/esp/57.mp3',
 	 img:       'common/images/words/57.png'
 	},
	{id:        58,
	 Eng_name:  'Ice',
	 Eng_audio: 'common/audio/words/eng/58.mp3',
	 Por_name:  'Gelo',
	 Por_audio: 'common/audio/words/por/58.mp3',
	 Esp_name:  'Hielo',
	 Esp_audio: 'common/audio/words/esp/58.mp3',
 	 img:       'common/images/words/58.png'
 	},
	{id:        59,
	 Eng_name:  'Iguana',
	 Eng_audio: 'common/audio/words/eng/59.mp3',
	 Por_name:  'Iguana',
	 Por_audio: 'common/audio/words/por/59.mp3',
	 Esp_name:  'Iguana',
	 Esp_audio: 'common/audio/words/esp/59.mp3',
 	 img:       'common/images/words/59.png'
 	},
	{id:        60,
	 Eng_name:  'Iceberg',
	 Eng_audio: 'common/audio/words/eng/60.mp3',
	 Por_name:  'Icebergue',
	 Por_audio: 'common/audio/words/por/60.mp3',
	 Esp_name:  'Témpano',
	 Esp_audio: 'common/audio/words/esp/60.mp3',
 	 img:       'common/images/words/60.png'
 	},
	{id:        61,
	 Eng_name:  'Igloo',
	 Eng_audio: 'common/audio/words/eng/61.mp3',
	 Por_name:  'Iglu',
	 Por_audio: 'common/audio/words/por/61.mp3',
	 Esp_name:  'Iglú',
	 Esp_audio: 'common/audio/words/esp/61.mp3',
 	 img:       'common/images/words/61.png'
 	},
	{id:        62,
	 Eng_name:  'iPod',
	 Eng_audio: 'common/audio/words/eng/62.mp3',
	 Por_name:  'iPod',
	 Por_audio: 'common/audio/words/por/62.mp3',
	 Esp_name:  'iPod',
	 Esp_audio: 'common/audio/words/esp/62.mp3',
 	 img:       'common/images/words/62.png'
 	},
	{id:        63,
	 Eng_name:  'Island',
	 Eng_audio: 'common/audio/words/eng/63.mp3',
	 Por_name:  'Isla',
	 Por_audio: 'common/audio/words/por/63.mp3',
	 Esp_name:  'Ilha',
	 Esp_audio: 'common/audio/words/esp/63.mp3',
 	 img:       'common/images/words/63.png'
 	},
	{id:        64,
	 Eng_name:  'Iron',
	 Eng_audio: 'common/audio/words/eng/64.mp3',
	 Por_name:  'Ferro',
	 Por_audio: 'common/audio/words/por/64.mp3',
	 Esp_name:  'Hierro',
	 Esp_audio: 'common/audio/words/esp/64.mp3',
 	 img:       'common/images/words/64.png'
 	},
	{id:        65,
	 Eng_name:  'Pants',
	 Eng_audio: 'common/audio/words/eng/65.mp3',
	 Por_name:  'Calça',
	 Por_audio: 'common/audio/words/por/65.mp3',
	 Esp_name:  'Pantalones',
	 Esp_audio: 'common/audio/words/esp/65.mp3',
 	 img:       'common/images/words/65.png'
 	},
	{id:        66,
	 Eng_name:  'Jacket',
	 Eng_audio: 'common/audio/words/eng/66.mp3',
	 Por_name:  'Jaqueta',
	 Por_audio: 'common/audio/words/por/66.mp3',
	 Esp_name:  'Chaqueta',
	 Esp_audio: 'common/audio/words/esp/66.mp3',
 	 img:       'common/images/words/66.png'
 	},
	{id:        67,
	 Eng_name:  'Jackfruit',
	 Eng_audio: 'common/audio/words/eng/67.mp3',
	 Por_name:  'Jaca',
	 Por_audio: 'common/audio/words/por/67.mp3',
	 Esp_name:  'Yaca',
	 Esp_audio: 'common/audio/words/esp/67.mp3',
 	 img:       'common/images/words/67.png'
 	},
	{id:        68,
	 Eng_name:  'Jam',
	 Eng_audio: 'common/audio/words/eng/68.mp3',
	 Por_name:  'Geléia',
	 Por_audio: 'common/audio/words/por/68.mp3',
	 Esp_name:  'Mermelada',
	 Esp_audio: 'common/audio/words/esp/68.mp3',
 	 img:       'common/images/words/68.png'
 	},
	{id:        69,
	 Eng_name:  'Shorts',
	 Eng_audio: 'common/audio/words/eng/69.mp3',
	 Por_name:  'Bermuda',
	 Por_audio: 'common/audio/words/por/69.mp3',
	 Esp_name:  'Pantalones Cortos',
	 Esp_audio: 'common/audio/words/esp/69.mp3',
 	 img:       'common/images/words/69.png'
 	},
	{id:        70,
	 Eng_name:  'Jello',
	 Eng_audio: 'common/audio/words/eng/70.mp3',
	 Por_name:  'Gelatina',
	 Por_audio: 'common/audio/words/por/70.mp3',
	 Esp_name:  'Gelatina',
	 Esp_audio: 'common/audio/words/esp/70.mp3',
 	 img:       'common/images/words/70.png'
 	},
	{id:        71,
	 Eng_name:  'Juice',
	 Eng_audio: 'common/audio/words/eng/71.mp3',
	 Por_name:  'Suco',
	 Por_audio: 'common/audio/words/por/71.mp3',
	 Esp_name:  'Jugo',
	 Esp_audio: 'common/audio/words/esp/71.mp3',
 	 img:       'common/images/words/71.png'
 	},
	{id:        72,
	 Eng_name:  'Jupiter',
	 Eng_audio: 'common/audio/words/eng/72.mp3',
	 Por_name:  'Júpiter',
	 Por_audio: 'common/audio/words/por/72.mp3',
	 Esp_name:  'Júpiter',
	 Esp_audio: 'common/audio/words/esp/72.mp3',
 	 img:       'common/images/words/72.png'
 	},
	{id:        73,
	 Eng_name:  'Jar',
	 Eng_audio: 'common/audio/words/eng/73.mp3',
	 Por_name:  'Jarra',
	 Por_audio: 'common/audio/words/por/73.mp3',
	 Esp_name:  'Tarro',
	 Esp_audio: 'common/audio/words/esp/73.mp3',
 	 img:       'common/images/words/73.png'
 	},
	{id:        74,
	 Eng_name:  'Kangaroo',
	 Eng_audio: 'common/audio/words/eng/74.mp3',
	 Por_name:  'Canguru',
	 Por_audio: 'common/audio/words/por/74.mp3',
	 Esp_name:  'Canguro',
	 Esp_audio: 'common/audio/words/esp/74.mp3',
 	 img:       'common/images/words/74.png'
 	},
	{id:        75,
	 Eng_name:  'Seaweed',
	 Eng_audio: 'common/audio/words/eng/75.mp3',
	 Por_name:  'Alga',
	 Por_audio: 'common/audio/words/por/75.mp3',
	 Esp_name:  'Alga',
	 Esp_audio: 'common/audio/words/esp/75.mp3',
 	 img:       'common/images/words/75.png'
 	},
	{id:        76,
	 Eng_name:  'Kids',
	 Eng_audio: 'common/audio/words/eng/76.mp3',
	 Por_name:  'Crianças',
	 Por_audio: 'common/audio/words/por/76.mp3',
	 Esp_name:  'Niños',
	 Esp_audio: 'common/audio/words/esp/76.mp3',
 	 img:       'common/images/words/76.png'
 	},
	{id:        77,
	 Eng_name:  'Ketchup',
	 Eng_audio: 'common/audio/words/eng/77.mp3',
	 Por_name:  'Ketchup',
	 Por_audio: 'common/audio/words/por/77.mp3',
	 Esp_name:  'Salsa de tomate',
	 Esp_audio: 'common/audio/words/esp/77.mp3',
 	 img:       'common/images/words/77.png'
 	},
	{id:        78,
	 Eng_name:  'Kiwi',
	 Eng_audio: 'common/audio/words/eng/78.mp3',
	 Por_name:  'Kiwi',
	 Por_audio: 'common/audio/words/por/78.mp3',
	 Esp_name:  'Kiwi',
	 Esp_audio: 'common/audio/words/esp/78.mp3',
 	 img:       'common/images/words/78.png'
 	},
	{id:        79,
	 Eng_name:  'Keys',
	 Eng_audio: 'common/audio/words/eng/79.mp3',
	 Por_name:  'Chaves',
	 Por_audio: 'common/audio/words/por/79.mp3',
	 Esp_name:  'Llaves',
	 Esp_audio: 'common/audio/words/esp/79.mp3',
 	 img:       'common/images/words/79.png'
 	},
	{id:        80,
	 Eng_name:  'Kettle',
	 Eng_audio: 'common/audio/words/eng/80.mp3',
	 Por_name:  'Chaleira',
	 Por_audio: 'common/audio/words/por/80.mp3',
	 Esp_name:  'Tetera',
	 Esp_audio: 'common/audio/words/esp/80.mp3',
 	 img:       'common/images/words/80.png'
 	},
	{id:        81,
	 Eng_name:  'Kite',
	 Eng_audio: 'common/audio/words/eng/81.mp3',
	 Por_name:  'Pipa',
	 Por_audio: 'common/audio/words/por/81.mp3',
	 Esp_name:  'Cometa',
	 Esp_audio: 'common/audio/words/esp/81.mp3',
 	 img:       'common/images/words/81.png'
 	},
	{id:        82,
	 Eng_name:  'Candle',
	 Eng_audio: 'common/audio/words/eng/82.mp3',
	 Por_name:  'Vela',
	 Por_audio: 'common/audio/words/por/82.mp3',
	 Esp_name:  'Vela',
	 Esp_audio: 'common/audio/words/esp/82.mp3',
 	 img:       'common/images/words/82.png'
 	},
	{id:        83,
	 Eng_name:  'Bucket',
	 Eng_audio: 'common/audio/words/eng/83.mp3',
	 Por_name:  'Balde',
	 Por_audio: 'common/audio/words/por/83.mp3',
	 Esp_name:  'Cangilón',
	 Esp_audio: 'common/audio/words/esp/83.mp3',
 	 img:       'common/images/words/83.png'
 	},
	{id:        84,
	 Eng_name:  'House',
	 Eng_audio: 'common/audio/words/eng/84.mp3',
	 Por_name:  'Casa',
	 Por_audio: 'common/audio/words/por/84.mp3',
	 Esp_name:  'Casa',
	 Esp_audio: 'common/audio/words/esp/84.mp3',
 	 img:       'common/images/words/84.png'
 	},
	{id:        85,
	 Eng_name:  'Basket',
	 Eng_audio: 'common/audio/words/eng/85.mp3',
	 Por_name:  'Cesta',
	 Por_audio: 'common/audio/words/por/85.mp3',
	 Esp_name:  'Cesta',
	 Esp_audio: 'common/audio/words/esp/85.mp3',
 	 img:       'common/images/words/85.png'
 	},
	{id:        86,
	 Eng_name:  'Baby',
	 Eng_audio: 'common/audio/words/eng/86.mp3',
	 Por_name:  'Bebê',
	 Por_audio: 'common/audio/words/por/86.mp3',
	 Esp_name:  'Bebé',
	 Esp_audio: 'common/audio/words/esp/86.mp3',
 	 img:       'common/images/words/86.png'
 	},
	{id:        87,
	 Eng_name:  'Backpack',
	 Eng_audio: 'common/audio/words/eng/87.mp3',
	 Por_name:  'Mochila',
	 Por_audio: 'common/audio/words/por/87.mp3',
	 Esp_name:  'Mochila',
	 Esp_audio: 'common/audio/words/esp/87.mp3',
 	 img:       'common/images/words/87.png'
 	},
	{id:        88,
	 Eng_name:  'Fork',
	 Eng_audio: 'common/audio/words/eng/88.mp3',
	 Por_name:  'Garfo',
	 Por_audio: 'common/audio/words/por/88.mp3',
	 Esp_name:  'Tenedor',
	 Esp_audio: 'common/audio/words/esp/88.mp3',
 	 img:       'common/images/words/88.png'
 	},
	{id:        89,
	 Eng_name:  'Grass',
	 Eng_audio: 'common/audio/words/eng/89.mp3',
	 Por_name:  'Grama',
	 Por_audio: 'common/audio/words/por/89.mp3',
	 Esp_name:  'Césped',
	 Esp_audio: 'common/audio/words/esp/89.mp3',
 	 img:       'common/images/words/89.png'
 	},
	{id:        90,
	 Eng_name:  'Lamp',
	 Eng_audio: 'common/audio/words/eng/90.mp3',
	 Por_name:  'Lâmpada',
	 Por_audio: 'common/audio/words/por/90.mp3',
	 Esp_name:  'Lámpara',
	 Esp_audio: 'common/audio/words/esp/90.mp3',
 	 img:       'common/images/words/90.png'
 	},
	{id:        91,
	 Eng_name:  'Lion',
	 Eng_audio: 'common/audio/words/eng/91.mp3',
	 Por_name:  'Leão',
	 Por_audio: 'common/audio/words/por/91.mp3',
	 Esp_name:  'León',
	 Esp_audio: 'common/audio/words/esp/91.mp3',
 	 img:       'common/images/words/91.png'
 	},
	{id:        92,
	 Eng_name:  'Leaf',
	 Eng_audio: 'common/audio/words/eng/92.mp3',
	 Por_name:  'Folha',
	 Por_audio: 'common/audio/words/por/92.mp3',
	 Esp_name:  'Hoja',
	 Esp_audio: 'common/audio/words/esp/92.mp3',
 	 img:       'common/images/words/92.png'
 	},
	{id:        93,
	 Eng_name:  'Lime',
	 Eng_audio: 'common/audio/words/eng/93.mp3',
	 Por_name:  'Limão',
	 Por_audio: 'common/audio/words/por/93.mp3',
	 Esp_name:  'Lima',
	 Esp_audio: 'common/audio/words/esp/93.mp3',
 	 img:       'common/images/words/93.png'
 	},
	{id:        94,
	 Eng_name:  'Lobster',
	 Eng_audio: 'common/audio/words/eng/94.mp3',
	 Por_name:  'Lagosta',
	 Por_audio: 'common/audio/words/por/94.mp3',
	 Esp_name:  'Langosta',
	 Esp_audio: 'common/audio/words/esp/94.mp3',
 	 img:       'common/images/words/94.png'
 	},
	{id:        95,
	 Eng_name:  'Marker',
	 Eng_audio: 'common/audio/words/eng/95.mp3',
	 Por_name:  'Marcador',
	 Por_audio: 'common/audio/words/por/95.mp3',
	 Esp_name:  'Marcador',
	 Esp_audio: 'common/audio/words/esp/95.mp3',
 	 img:       'common/images/words/95.png'
 	},
	{id:        96,
	 Eng_name:  'Monkey',
	 Eng_audio: 'common/audio/words/eng/96.mp3',
	 Por_name:  'Macaco',
	 Por_audio: 'common/audio/words/por/96.mp3',
	 Esp_name:  'Mono',
	 Esp_audio: 'common/audio/words/esp/96.mp3',
 	 img:       'common/images/words/96.png'
 	},
	{id:        97,
	 Eng_name:  'Motorcycle',
	 Eng_audio: 'common/audio/words/eng/97.mp3',
	 Por_name:  'Môto',
	 Por_audio: 'common/audio/words/por/97.mp3',
	 Esp_name:  'Motocicleta',
	 Esp_audio: 'common/audio/words/esp/97.mp3',
 	 img:       'common/images/words/97.png'
 	},
	{id:        98,
	 Eng_name:  'Net',
	 Eng_audio: 'common/audio/words/eng/98.mp3',
	 Por_name:  'Rede',
	 Por_audio: 'common/audio/words/por/98.mp3',
	 Esp_name:  'Red',
	 Esp_audio: 'common/audio/words/esp/98.mp3',
 	 img:       'common/images/words/98.png'
 	},
	{id:        99,
	 Eng_name:  'Nest',
	 Eng_audio: 'common/audio/words/eng/99.mp3',
	 Por_name:  'Ninho',
	 Por_audio: 'common/audio/words/por/99.mp3',
	 Esp_name:  'Nido',
	 Esp_audio: 'common/audio/words/esp/99.mp3',
 	 img:       'common/images/words/99.png'
 	},
	{id:        100,
	 Eng_name:  'Oranges',
	 Eng_audio: 'common/audio/words/eng/100.mp3',
	 Por_name:  'Laranjas',
	 Por_audio: 'common/audio/words/por/100.mp3',
	 Esp_name:  'Naranjas',
	 Esp_audio: 'common/audio/words/esp/100.mp3',
 	 img:       'common/images/words/100.png'
 	},
	{id:        101,
	 Eng_name:  'Octopus',
	 Eng_audio: 'common/audio/words/eng/101.mp3',
	 Por_name:  'Polvo',
	 Por_audio: 'common/audio/words/por/101.mp3',
	 Esp_name:  'Pulpo',
	 Esp_audio: 'common/audio/words/esp/101.mp3',
 	 img:       'common/images/words/101.png'
 	},
	{id:        102,
	 Eng_name:  'Owl',
	 Eng_audio: 'common/audio/words/eng/102.mp3',
	 Por_name:  'Coruja',
	 Por_audio: 'common/audio/words/por/102.mp3',
	 Esp_name:  'Búho',
	 Esp_audio: 'common/audio/words/esp/102.mp3',
 	 img:       'common/images/words/102.png'
 	},
	{id:        103,
	 Eng_name:  'Olives',
	 Eng_audio: 'common/audio/words/eng/103.mp3',
	 Por_name:  'Azeitonas',
	 Por_audio: 'common/audio/words/por/103.mp3',
	 Esp_name:  'Aceitunas',
	 Esp_audio: 'common/audio/words/esp/103.mp3',
 	 img:       'common/images/words/103.png'
 	},
	{id:        104,
	 Eng_name:  'Penguin',
	 Eng_audio: 'common/audio/words/eng/104.mp3',
	 Por_name:  'Pinguim',
	 Por_audio: 'common/audio/words/por/104.mp3',
	 Esp_name:  'Pingüino',
	 Esp_audio: 'common/audio/words/esp/104.mp3',
 	 img:       'common/images/words/104.png'
 	},
	{id:        105,
	 Eng_name:  'Pizza',
	 Eng_audio: 'common/audio/words/eng/105.mp3',
	 Por_name:  'Pizza',
	 Por_audio: 'common/audio/words/por/105.mp3',
	 Esp_name:  'Pizza',
	 Esp_audio: 'common/audio/words/esp/105.mp3',
 	 img:       'common/images/words/105.png'
 	},
	{id:        106,
	 Eng_name:  'Pirate',
	 Eng_audio: 'common/audio/words/eng/106.mp3',
	 Por_name:  'Pirata',
	 Por_audio: 'common/audio/words/por/106.mp3',
	 Esp_name:  'Pirata',
	 Esp_audio: 'common/audio/words/esp/106.mp3',
 	 img:       'common/images/words/106.png'
 	},
	{id:        107,
	 Eng_name:  'Pencil',
	 Eng_audio: 'common/audio/words/eng/107.mp3',
	 Por_name:  'Lápis',
	 Por_audio: 'common/audio/words/por/107.mp3',
	 Esp_name:  'Lápiz',
	 Esp_audio: 'common/audio/words/esp/107.mp3',
 	 img:       'common/images/words/107.png'
 	},
	{id:        108,
	 Eng_name:  'Pig',
	 Eng_audio: 'common/audio/words/eng/108.mp3',
	 Por_name:  'Porco',
	 Por_audio: 'common/audio/words/por/108.mp3',
	 Esp_name:  'Cerdo',
	 Esp_audio: 'common/audio/words/esp/108.mp3',
 	 img:       'common/images/words/108.png'
 	},
	{id:        109,
	 Eng_name:  'Porcupine',
	 Eng_audio: 'common/audio/words/eng/109.mp3',
	 Por_name:  'Porco-espinho',
	 Por_audio: 'common/audio/words/por/109.mp3',
	 Esp_name:  'Puerco espín',
	 Esp_audio: 'common/audio/words/esp/109.mp3',
 	 img:       'common/images/words/109.png'
 	},
	{id:        110,
	 Eng_name:  'Panda',
	 Eng_audio: 'common/audio/words/eng/110.mp3',
	 Por_name:  'Panda',
	 Por_audio: 'common/audio/words/por/110.mp3',
	 Esp_name:  'Panda',
	 Esp_audio: 'common/audio/words/esp/110.mp3',
 	 img:       'common/images/words/110.png'
 	},
	{id:        111,
	 Eng_name:  'Quilt',
	 Eng_audio: 'common/audio/words/eng/111.mp3',
	 Por_name:  'Colcha',
	 Por_audio: 'common/audio/words/por/111.mp3',
	 Esp_name:  'Edredón',
	 Esp_audio: 'common/audio/words/esp/111.mp3',
 	 img:       'common/images/words/111.png'
 	},
	{id:        112,
	 Eng_name:  'Queen',
	 Eng_audio: 'common/audio/words/eng/112.mp3',
	 Por_name:  'Rainha',
	 Por_audio: 'common/audio/words/por/112.mp3',
	 Esp_name:  'Reina',
	 Esp_audio: 'common/audio/words/esp/112.mp3',
 	 img:       'common/images/words/112.png'
 	},
	{id:        113,
	 Eng_name:  'Quartz',
	 Eng_audio: 'common/audio/words/eng/113.mp3',
	 Por_name:  'Quartzo',
	 Por_audio: 'common/audio/words/por/113.mp3',
	 Esp_name:  'Cuarzo',
	 Esp_audio: 'common/audio/words/esp/113.mp3',
 	 img:       'common/images/words/113.png'
 	},
	{id:        114,
	 Eng_name:  'Rake',
	 Eng_audio: 'common/audio/words/eng/114.mp3',
	 Por_name:  'Ancinho',
	 Por_audio: 'common/audio/words/por/114.mp3',
	 Esp_name:  'Rastrillo',
	 Esp_audio: 'common/audio/words/esp/114.mp3',
 	 img:       'common/images/words/114.png'
 	},
	{id:        115,
	 Eng_name:  'Rainbow',
	 Eng_audio: 'common/audio/words/eng/115.mp3',
	 Por_name:  'Arco iris',
	 Por_audio: 'common/audio/words/por/115.mp3',
	 Esp_name:  'Arco iris',
	 Esp_audio: 'common/audio/words/esp/115.mp3',
 	 img:       'common/images/words/115.png'
 	},
	{id:        116,
	 Eng_name:  'Rabbit',
	 Eng_audio: 'common/audio/words/eng/116.mp3',
	 Por_name:  'Coelho',
	 Por_audio: 'common/audio/words/por/116.mp3',
	 Esp_name:  'Conejo',
	 Esp_audio: 'common/audio/words/esp/116.mp3',
 	 img:       'common/images/words/116.png'
 	},
	{id:        117,
	 Eng_name:  'Ring',
	 Eng_audio: 'common/audio/words/eng/117.mp3',
	 Por_name:  'Anel',
	 Por_audio: 'common/audio/words/por/117.mp3',
	 Esp_name:  'Anillo',
	 Esp_audio: 'common/audio/words/esp/117.mp3',
 	 img:       'common/images/words/117.png'
 	},
	{id:        118,
	 Eng_name:  'Snake',
	 Eng_audio: 'common/audio/words/eng/118.mp3',
	 Por_name:  'Cobra',
	 Por_audio: 'common/audio/words/por/118.mp3',
	 Esp_name:  'Serpiente',
	 Esp_audio: 'common/audio/words/esp/118.mp3',
 	 img:       'common/images/words/118.png'
 	},
	{id:        119,
	 Eng_name:  'Scissors',
	 Eng_audio: 'common/audio/words/eng/119.mp3',
	 Por_name:  'Tesouras',
	 Por_audio: 'common/audio/words/por/119.mp3',
	 Esp_name:  'Tijeras',
	 Esp_audio: 'common/audio/words/esp/119.mp3',
 	 img:       'common/images/words/119.png'
 	},
	{id:        120,
	 Eng_name:  'Stairs',
	 Eng_audio: 'common/audio/words/eng/120.mp3',
	 Por_name:  'Escada',
	 Por_audio: 'common/audio/words/por/120.mp3',
	 Esp_name:  'Escalera',
	 Esp_audio: 'common/audio/words/esp/120.mp3',
 	 img:       'common/images/words/120.png'
 	},
	{id:        121,
	 Eng_name:  'Skateboard',
	 Eng_audio: 'common/audio/words/eng/121.mp3',
	 Por_name:  'Skate',
	 Por_audio: 'common/audio/words/por/121.mp3',
	 Esp_name:  'Patineta',
	 Esp_audio: 'common/audio/words/esp/121.mp3',
 	 img:       'common/images/words/121.png'
 	},
	{id:        122,
	 Eng_name:  'Spoon',
	 Eng_audio: 'common/audio/words/eng/122.mp3',
	 Por_name:  'Colher',
	 Por_audio: 'common/audio/words/por/122.mp3',
	 Esp_name:  'Cuchara',
	 Esp_audio: 'common/audio/words/esp/122.mp3',
 	 img:       'common/images/words/122.png'
 	},
	{id:        123,
	 Eng_name:  'Sheep',
	 Eng_audio: 'common/audio/words/eng/123.mp3',
	 Por_name:  'Ovelha',
	 Por_audio: 'common/audio/words/por/123.mp3',
	 Esp_name:  'Oveja',
	 Esp_audio: 'common/audio/words/esp/123.mp3',
 	 img:       'common/images/words/123.png'
 	},
	{id:        124,
	 Eng_name:  'Snail',
	 Eng_audio: 'common/audio/words/eng/124.mp3',
	 Por_name:  'Caracol',
	 Por_audio: 'common/audio/words/por/124.mp3',
	 Esp_name:  'Caracol',
	 Esp_audio: 'common/audio/words/esp/124.mp3',
 	 img:       'common/images/words/124.png'
 	},
	{id:        125,
	 Eng_name:  'Strawberries',
	 Eng_audio: 'common/audio/words/eng/125.mp3',
	 Por_name:  'Morangos',
	 Por_audio: 'common/audio/words/por/125.mp3',
	 Esp_name:  'Fresas',
	 Esp_audio: 'common/audio/words/esp/125.mp3',
 	 img:       'common/images/words/125.png'
 	},
	{id:        126,
	 Eng_name:  'Sandles',
	 Eng_audio: 'common/audio/words/eng/126.mp3',
	 Por_name:  'Sandálias',
	 Por_audio: 'common/audio/words/por/126.mp3',
	 Esp_name:  'Sandalias',
	 Esp_audio: 'common/audio/words/esp/126.mp3',
 	 img:       'common/images/words/126.png'
 	},
	{id:        127,
	 Eng_name:  'Shoes',
	 Eng_audio: 'common/audio/words/eng/127.mp3',
	 Por_name:  'Sapatos',
	 Por_audio: 'common/audio/words/por/127.mp3',
	 Esp_name:  'Zapatos',
	 Esp_audio: 'common/audio/words/esp/127.mp3',
 	 img:       'common/images/words/127.png'
 	},
	{id:        128,
	 Eng_name:  'Stars',
	 Eng_audio: 'common/audio/words/eng/128.mp3',
	 Por_name:  'Estrelas',
	 Por_audio: 'common/audio/words/por/128.mp3',
	 Esp_name:  'Estrellas',
	 Esp_audio: 'common/audio/words/esp/128.mp3',
 	 img:       'common/images/words/128.png'
 	},
	{id:        129,
	 Eng_name:  'Ticket',
	 Eng_audio: 'common/audio/words/eng/129.mp3',
	 Por_name:  'Bilhete',
	 Por_audio: 'common/audio/words/por/129.mp3',
	 Esp_name:  'Boleto',
	 Esp_audio: 'common/audio/words/esp/129.mp3',
 	 img:       'common/images/words/129.png'
 	},
	{id:        130,
	 Eng_name:  'Table',
	 Eng_audio: 'common/audio/words/eng/130.mp3',
	 Por_name:  'Mesa',
	 Por_audio: 'common/audio/words/por/130.mp3',
	 Esp_name:  'Mesa',
	 Esp_audio: 'common/audio/words/esp/130.mp3',
 	 img:       'common/images/words/130.png'
 	},
	{id:        131,
	 Eng_name:  'Trampoline',
	 Eng_audio: 'common/audio/words/eng/131.mp3',
	 Por_name:  'Trampolim',
	 Por_audio: 'common/audio/words/por/131.mp3',
	 Esp_name:  'Trampolín',
	 Esp_audio: 'common/audio/words/esp/131.mp3',
 	 img:       'common/images/words/131.png'
 	},
	{id:        132,
	 Eng_name:  'Tiger',
	 Eng_audio: 'common/audio/words/eng/132.mp3',
	 Por_name:  'Tigre',
	 Por_audio: 'common/audio/words/por/132.mp3',
	 Esp_name:  'Tigre',
	 Esp_audio: 'common/audio/words/esp/132.mp3',
 	 img:       'common/images/words/132.png'
 	},
	{id:        133,
	 Eng_name:  'Tricycle',
	 Eng_audio: 'common/audio/words/eng/133.mp3',
	 Por_name:  'Triciclo',
	 Por_audio: 'common/audio/words/por/133.mp3',
	 Esp_name:  'Triciclo',
	 Esp_audio: 'common/audio/words/esp/133.mp3',
 	 img:       'common/images/words/133.png'
 	},
	{id:        134,
	 Eng_name:  'Toothbrush',
	 Eng_audio: 'common/audio/words/eng/134.mp3',
	 Por_name:  'Escova de dente',
	 Por_audio: 'common/audio/words/por/134.mp3',
	 Esp_name:  'Cepillo de dientes',
	 Esp_audio: 'common/audio/words/esp/134.mp3',
 	 img:       'common/images/words/134.png'
 	},
	{id:        135,
	 Eng_name:  'Truck',
	 Eng_audio: 'common/audio/words/eng/135.mp3',
	 Por_name:  'Caminhão',
	 Por_audio: 'common/audio/words/por/135.mp3',
	 Esp_name:  'Camión',
	 Esp_audio: 'common/audio/words/esp/135.mp3',
 	 img:       'common/images/words/135.png'
 	},
	{id:        136,
	 Eng_name:  'Tent',
	 Eng_audio: 'common/audio/words/eng/136.mp3',
	 Por_name:  'Tenda',
	 Por_audio: 'common/audio/words/por/136.mp3',
	 Esp_name:  'Tienda',
	 Esp_audio: 'common/audio/words/esp/136.mp3',
 	 img:       'common/images/words/136.png'
 	},
	{id:        137,
	 Eng_name:  'Turtle',
	 Eng_audio: 'common/audio/words/eng/137.mp3',
	 Por_name:  'Tartaruga',
	 Por_audio: 'common/audio/words/por/137.mp3',
	 Esp_name:  'Tortuga',
	 Esp_audio: 'common/audio/words/esp/137.mp3',
 	 img:       'common/images/words/137.png'
 	},
	{id:        138,
	 Eng_name:  'Unicorn',
	 Eng_audio: 'common/audio/words/eng/138.mp3',
	 Por_name:  'Unicórnio',
	 Por_audio: 'common/audio/words/por/138.mp3',
	 Esp_name:  'Unicornio',
	 Esp_audio: 'common/audio/words/esp/138.mp3',
 	 img:       'common/images/words/138.png'
 	},
	{id:        139,
	 Eng_name:  'Unicycle',
	 Eng_audio: 'common/audio/words/eng/139.mp3',
	 Por_name:  'Monociclo',
	 Por_audio: 'common/audio/words/por/139.mp3',
	 Esp_name:  'Monociclo',
	 Esp_audio: 'common/audio/words/esp/139.mp3',
 	 img:       'common/images/words/139.png'
 	},
	{id:        140,
	 Eng_name:  'Umbrella',
	 Eng_audio: 'common/audio/words/eng/140.mp3',
	 Por_name:  'Guarda-chuva',
	 Por_audio: 'common/audio/words/por/140.mp3',
	 Esp_name:  'Paraguas',
	 Esp_audio: 'common/audio/words/esp/140.mp3',
 	 img:       'common/images/words/140.png'
 	},
	{id:        141,
	 Eng_name:  'Vegetables',
	 Eng_audio: 'common/audio/words/eng/141.mp3',
	 Por_name:  'Legumes',
	 Por_audio: 'common/audio/words/por/141.mp3',
	 Esp_name:  'Vegetales',
	 Esp_audio: 'common/audio/words/esp/141.mp3',
 	 img:       'common/images/words/141.png'
 	},
	{id:        142,
	 Eng_name:  'Violin',
	 Eng_audio: 'common/audio/words/eng/142.mp3',
	 Por_name:  'Violino',
	 Por_audio: 'common/audio/words/por/142.mp3',
	 Esp_name:  'Violín',
	 Esp_audio: 'common/audio/words/esp/142.mp3',
 	 img:       'common/images/words/142.png'
 	},
	{id:        143,
	 Eng_name:  'Volcano',
	 Eng_audio: 'common/audio/words/eng/143.mp3',
	 Por_name:  'Vulcão',
	 Por_audio: 'common/audio/words/por/143.mp3',
	 Esp_name:  'Volcán',
	 Esp_audio: 'common/audio/words/esp/143.mp3',
 	 img:       'common/images/words/143.png'
 	},
	{id:        144,
	 Eng_name:  'Pepper',
	 Eng_audio: 'common/audio/words/eng/144.mp3',
	 Por_name:  'Pimentão',
	 Por_audio: 'common/audio/words/por/144.mp3',
	 Esp_name:  'Pimiento',
	 Esp_audio: 'common/audio/words/esp/144.mp3',
 	 img:       'common/images/words/144.png'
 	},
	{id:        145,
	 Eng_name:  'Asparagus',
	 Eng_audio: 'common/audio/words/eng/145.mp3',
	 Por_name:  'Aspargo',
	 Por_audio: 'common/audio/words/por/145.mp3',
	 Esp_name:  'Espárragos',
	 Esp_audio: 'common/audio/words/esp/145.mp3',
 	 img:       'common/images/words/145.png'
 	},
	{id:        146,
	 Eng_name:  'Pumpkin',
	 Eng_audio: 'common/audio/words/eng/146.mp3',
	 Por_name:  'Abóbora',
	 Por_audio: 'common/audio/words/por/146.mp3',
	 Esp_name:  'Calabaza',
	 Esp_audio: 'common/audio/words/esp/146.mp3',
 	 img:       'common/images/words/146.png'
 	},
	{id:        147,
	 Eng_name:  'Water',
	 Eng_audio: 'common/audio/words/eng/147.mp3',
	 Por_name:  'Água',
	 Por_audio: 'common/audio/words/por/147.mp3',
	 Esp_name:  'Agua',
	 Esp_audio: 'common/audio/words/esp/147.mp3',
 	 img:       'common/images/words/147.png'
 	},
	{id:        148,
	 Eng_name:  'Xenoceratops',
	 Eng_audio: 'common/audio/words/eng/148.mp3',
	 Por_name:  'Xenoceratops Foremostensis',
	 Por_audio: 'common/audio/words/por/148.mp3',
	 Esp_name:  'Xenoceratops',
	 Esp_audio: 'common/audio/words/esp/148.mp3',
 	 img:       'common/images/words/148.png'
 	},
	{id:        149,
	 Eng_name:  'Whale',
	 Eng_audio: 'common/audio/words/eng/149.mp3',
	 Por_name:  'Baleia',
	 Por_audio: 'common/audio/words/por/149.mp3',
	 Esp_name:  'Ballena',
	 Esp_audio: 'common/audio/words/esp/149.mp3',
 	 img:       'common/images/words/149.png'
 	},
	{id:        150,
	 Eng_name:  'Wheat',
	 Eng_audio: 'common/audio/words/eng/150.mp3',
	 Por_name:  'Trigo',
	 Por_audio: 'common/audio/words/por/150.mp3',
	 Esp_name:  'Trigo',
	 Esp_audio: 'common/audio/words/esp/150.mp3',
 	 img:       'common/images/words/150.png'
 	},
	{id:        151,
	 Eng_name:  'Wagon',
	 Eng_audio: 'common/audio/words/eng/151.mp3',
	 Por_name:  'Vagão',
	 Por_audio: 'common/audio/words/por/151.mp3',
	 Esp_name:  'Vagón',
	 Esp_audio: 'common/audio/words/esp/151.mp3',
 	 img:       'common/images/words/151.png'
 	},
	{id:        152,
	 Eng_name:  'Wheel',
	 Eng_audio: 'common/audio/words/eng/152.mp3',
	 Por_name:  'Roda',
	 Por_audio: 'common/audio/words/por/152.mp3',
	 Esp_name:  'Rueda',
	 Esp_audio: 'common/audio/words/esp/152.mp3',
 	 img:       'common/images/words/152.png'
 	},
	{id:        153,
	 Eng_name:  'Window',
	 Eng_audio: 'common/audio/words/eng/153.mp3',
	 Por_name:  'Janela',
	 Por_audio: 'common/audio/words/por/153.mp3',
	 Esp_name:  'Ventana',
	 Esp_audio: 'common/audio/words/esp/153.mp3',
 	 img:       'common/images/words/153.png'
 	},
	{id:        154,
	 Eng_name:  'Wood',
	 Eng_audio: 'common/audio/words/eng/154.mp3',
	 Por_name:  'Madeira',
	 Por_audio: 'common/audio/words/por/154.mp3',
	 Esp_name:  'Madera',
	 Esp_audio: 'common/audio/words/esp/154.mp3',
 	 img:       'common/images/words/154.png'
 	},
	{id:        155,
	 Eng_name:  'Walrus',
	 Eng_audio: 'common/audio/words/eng/155.mp3',
	 Por_name:  'Morsa',
	 Por_audio: 'common/audio/words/por/155.mp3',
	 Esp_name:  'Morsa',
	 Esp_audio: 'common/audio/words/esp/155.mp3',
 	 img:       'common/images/words/155.png'
 	},
	{id:        156,
	 Eng_name:  'Spider Web',
	 Eng_audio: 'common/audio/words/eng/156.mp3',
	 Por_name:  'Teia de aranha',
	 Por_audio: 'common/audio/words/por/156.mp3',
	 Esp_name:  'Telaraña',
	 Esp_audio: 'common/audio/words/esp/156.mp3',
 	 img:       'common/images/words/156.png'
 	},
	{id:        157,
	 Eng_name:  'Spider',
	 Eng_audio: 'common/audio/words/eng/157.mp3',
	 Por_name:  'Aranha',
	 Por_audio: 'common/audio/words/por/157.mp3',
	 Esp_name:  'Araña',
	 Esp_audio: 'common/audio/words/esp/157.mp3',
 	 img:       'common/images/words/157.png'
 	},
	{id:        158,
	 Eng_name:  'Xylophone',
	 Eng_audio: 'common/audio/words/eng/158.mp3',
	 Por_name:  'Xilofone',
	 Por_audio: 'common/audio/words/por/158.mp3',
	 Esp_name:  'Xilófono',
	 Esp_audio: 'common/audio/words/esp/158.mp3',
 	 img:       'common/images/words/158.png'
 	},
	{id:        159,
	 Eng_name:  'X-ray',
	 Eng_audio: 'common/audio/words/eng/159.mp3',
	 Por_name:  'Raio X',
	 Por_audio: 'common/audio/words/por/159.mp3',
	 Esp_name:  'radiografía',
	 Esp_audio: 'common/audio/words/esp/159.mp3',
 	 img:       'common/images/words/159.png'
 	},
	{id:        160,
	 Eng_name:  'Yarn',
	 Eng_audio: 'common/audio/words/eng/160.mp3',
	 Por_name:  'Lã',
	 Por_audio: 'common/audio/words/por/160.mp3',
	 Esp_name:  'Estambre',
	 Esp_audio: 'common/audio/words/esp/160.mp3',
 	 img:       'common/images/words/160.png'
 	},
	{id:        161,
	 Eng_name:  'Yo-yo',
	 Eng_audio: 'common/audio/words/eng/161.mp3',
	 Por_name:  'Ioiô',
	 Por_audio: 'common/audio/words/por/161.mp3',
	 Esp_name:  'Yoyó',
	 Esp_audio: 'common/audio/words/esp/161.mp3',
 	 img:       'common/images/words/161.png'
 	},
	{id:        162,
	 Eng_name:  'Yak',
	 Eng_audio: 'common/audio/words/eng/162.mp3',
	 Por_name:  'Iaque',
	 Por_audio: 'common/audio/words/por/162.mp3',
	 Esp_name:  'Yak',
	 Esp_audio: 'common/audio/words/esp/162.mp3',
 	 img:       'common/images/words/162.png'
 	},
	{id:        163,
	 Eng_name:  'Zipper',
	 Eng_audio: 'common/audio/words/eng/163.mp3',
	 Por_name:  'Zíper',
	 Por_audio: 'common/audio/words/por/163.mp3',
	 Esp_name:  'Cremallera',
	 Esp_audio: 'common/audio/words/esp/163.mp3',
 	 img:       'common/images/words/163.png'
 	},
	{id:        164,
	 Eng_name:  'Zig-zag',
	 Eng_audio: 'common/audio/words/eng/164.mp3',
	 Por_name:  'Ziguezague',
	 Por_audio: 'common/audio/words/por/164.mp3',
	 Esp_name:  'Zigzag',
	 Esp_audio: 'common/audio/words/esp/164.mp3',
 	 img:       'common/images/words/164.png'
 	},
	{id:        165,
	 Eng_name:  'Zebra',
	 Eng_audio: 'common/audio/words/eng/165.mp3',
	 Por_name:  'Zebra',
	 Por_audio: 'common/audio/words/por/165.mp3',
	 Esp_name:  'Cebra',
	 Esp_audio: 'common/audio/words/esp/165.mp3',
 	 img:       'common/images/words/165.png'
 	},
	{id:        166,
	 Eng_name:  'Syrup',
	 Eng_audio: 'common/audio/words/eng/166.mp3',
	 Por_name:  'Xarope',
	 Por_audio: 'common/audio/words/por/166.mp3',
	 Esp_name:  'Jarabe',
	 Esp_audio: 'common/audio/words/esp/166.mp3',
 	 img:       'common/images/words/166.png'
 	},
	{id:        167,
	 Eng_name:  'Teeth',
	 Eng_audio: 'common/audio/words/eng/167.mp3',
	 Por_name:  'Dentes',
	 Por_audio: 'common/audio/words/por/167.mp3',
	 Esp_name:  'Dientes',
	 Esp_audio: 'common/audio/words/esp/167.mp3',
 	 img:       'common/images/words/167.png'
 	},
	{id:        168,
	 Eng_name:  'Diamond',
	 Eng_audio: 'common/audio/words/eng/168.mp3',
	 Por_name:  'Diamante',
	 Por_audio: 'common/audio/words/por/168.mp3',
	 Esp_name:  'Diamante',
	 Esp_audio: 'common/audio/words/esp/168.mp3',
 	 img:       'common/images/words/168.png'
 	},
	{id:        169,
	 Eng_name:  'Alarm clock',
	 Eng_audio: 'common/audio/words/eng/169.mp3',
	 Por_name:  'Despertador',
	 Por_audio: 'common/audio/words/por/169.mp3',
	 Esp_name:  'Despertador',
	 Esp_audio: 'common/audio/words/esp/169.mp3',
 	 img:       'common/images/words/169.png'
 	},
	{id:        170,
	 Eng_name:  'Diary',
	 Eng_audio: 'common/audio/words/eng/170.mp3',
	 Por_name:  'Diário',
	 Por_audio: 'common/audio/words/por/170.mp3',
	 Esp_name:  'Diário',
	 Esp_audio: 'common/audio/words/esp/170.mp3',
 	 img:       'common/images/words/170.png'
 	},
	{id:        171,
	 Eng_name:  'Dictionary',
	 Eng_audio: 'common/audio/words/eng/171.mp3',
	 Por_name:  'Dicionário',
	 Por_audio: 'common/audio/words/por/171.mp3',
	 Esp_name:  'Diccionario',
	 Esp_audio: 'common/audio/words/esp/171.mp3',
 	 img:       'common/images/words/171.png'
 	},
	{id:        172,
	 Eng_name:  'Dart',
	 Eng_audio: 'common/audio/words/eng/172.mp3',
	 Por_name:  'Dardo',
	 Por_audio: 'common/audio/words/por/172.mp3',
	 Esp_name:  'Dardo',
	 Esp_audio: 'common/audio/words/esp/172.mp3',
 	 img:       'common/images/words/172.png'
 	},
	{id:        173,
	 Eng_name:  'Squirrel',
	 Eng_audio: 'common/audio/words/eng/173.mp3',
	 Por_name:  'Esquilo',
	 Por_audio: 'common/audio/words/por/173.mp3',
	 Esp_name:  'Ardilla',
	 Esp_audio: 'common/audio/words/esp/173.mp3',
 	 img:       'common/images/words/173.png'
 	},
	{id:        174,
	 Eng_name:  'Hippo',
	 Eng_audio: 'common/audio/words/eng/174.mp3',
	 Por_name:  'Hipopótamo',
	 Por_audio: 'common/audio/words/por/174.mp3',
	 Esp_name:  'Hipopótamo',
	 Esp_audio: 'common/audio/words/esp/174.mp3',
 	 img:       'common/images/words/174.png'
 	},
	{id:        175,
	 Eng_name:  'Spotlight',
	 Eng_audio: 'common/audio/words/eng/175.mp3',
	 Por_name:  'Holofote',
	 Por_audio: 'common/audio/words/por/175.mp3',
	 Esp_name:  'Foco',
	 Esp_audio: 'common/audio/words/esp/175.mp3',
 	 img:       'common/images/words/175.png'
 	},
	{id:        176,
	 Eng_name:  'Fire Hydrant',
	 Eng_audio: 'common/audio/words/eng/176.mp3',
	 Por_name:  'Hidrante',
	 Por_audio: 'common/audio/words/por/176.mp3',
	 Esp_name:  'Boca de Incendio',
	 Esp_audio: 'common/audio/words/esp/176.mp3',
 	 img:       'common/images/words/176.png'
 	},
	{id:        177,
	 Eng_name:  'Walnut',
	 Eng_audio: 'common/audio/words/eng/177.mp3',
	 Por_name:  'Noz',
	 Por_audio: 'common/audio/words/por/177.mp3',
	 Esp_name:  'Nuez',
	 Esp_audio: 'common/audio/words/esp/177.mp3',
 	 img:       'common/images/words/177.png'
 	},
	{id:        178,
	 Eng_name:  'Turnip',
	 Eng_audio: 'common/audio/words/eng/178.mp3',
	 Por_name:  'Nabo',
	 Por_audio: 'common/audio/words/por/178.mp3',
	 Esp_name:  'Nabo',
	 Esp_audio: 'common/audio/words/esp/178.mp3',
 	 img:       'common/images/words/178.png'
 	},
	{id:        179,
	 Eng_name:  'Flippers',
	 Eng_audio: 'common/audio/words/eng/179.mp3',
	 Por_name:  'Nadadeiras',
	 Por_audio: 'common/audio/words/por/179.mp3',
	 Esp_name:  'Aletas',
	 Esp_audio: 'common/audio/words/esp/179.mp3',
 	 img:       'common/images/words/179.png'
 	},
	{id:        180,
	 Eng_name:  'Laptop',
	 Eng_audio: 'common/audio/words/eng/180.mp3',
	 Por_name:  'Notebook',
	 Por_audio: 'common/audio/words/por/180.mp3',
	 Esp_name:  'Computadora Portátil',
	 Esp_audio: 'common/audio/words/esp/180.mp3',
 	 img:       'common/images/words/180.png'
 	},
	{id:        181,
	 Eng_name:  'Omelet',
	 Eng_audio: 'common/audio/words/eng/181.mp3',
	 Por_name:  'Omelete',
	 Por_audio: 'common/audio/words/por/181.mp3',
	 Esp_name:  'Torta de Huevo ',
	 Esp_audio: 'common/audio/words/esp/181.mp3',
 	 img:       'common/images/words/181.png'
 	},
	{id:        182,
	 Eng_name:  'Cranberry',
	 Eng_audio: 'common/audio/words/eng/182.mp3',
	 Por_name:  'Cranberry',
	 Por_audio: 'common/audio/words/por/182.mp3',
	 Esp_name:  'Arándano Agrio',
	 Esp_audio: 'common/audio/words/esp/182.mp3',
 	 img:       'common/images/words/182.png'
 	},
	{id:        183,
	 Eng_name:  'Urchin',
	 Eng_audio: 'common/audio/words/eng/183.mp3',
	 Por_name:  'Ouriço',
	 Por_audio: 'common/audio/words/por/183.mp3',
	 Esp_name:  'Erizo',
	 Esp_audio: 'common/audio/words/esp/183.mp3',
 	 img:       'common/images/words/183.png'
 	},
	{id:        184,
	 Eng_name:  'Waffle',
	 Eng_audio: 'common/audio/words/eng/184.mp3',
	 Por_name:  'Waffle',
	 Por_audio: 'common/audio/words/por/184.mp3',
	 Esp_name:  'Gofre',
	 Esp_audio: 'common/audio/words/esp/184.mp3',
 	 img:       'common/images/words/184.png'
 	},
	{id:        185,
	 Eng_name:  'walkie-talkie',
	 Eng_audio: 'common/audio/words/eng/185.mp3',
	 Por_name:  'walkie-talkie',
	 Por_audio: 'common/audio/words/por/185.mp3',
	 Esp_name:  'walkie-talkie',
	 Esp_audio: 'common/audio/words/esp/185.mp3',
 	 img:       'common/images/words/185.png'
 	},
	{id:        186,
	 Eng_name:  'Yogurt',
	 Eng_audio: 'common/audio/words/eng/186.mp3',
	 Por_name:  'Yorgute',
	 Por_audio: 'common/audio/words/por/186.mp3',
	 Esp_name:  'Yogur',
	 Esp_audio: 'common/audio/words/esp/186.mp3',
 	 img:       'common/images/words/186.png'
 	},
	{id:        187,
	 Eng_name:  'Yoga',
	 Eng_audio: 'common/audio/words/eng/187.mp3',
	 Por_name:  'Yoga',
	 Por_audio: 'common/audio/words/por/187.mp3',
	 Esp_name:  'Yoga',
	 Esp_audio: 'common/audio/words/esp/187.mp3',
 	 img:       'common/images/words/187.png'
 	},
	{id:        188,
	 Eng_name:  'Bus',
	 Eng_audio: 'common/audio/words/eng/188.mp3',
	 Por_name:  'Ônibus',
	 Por_audio: 'common/audio/words/por/188.mp3',
	 Esp_name:  'Autobús',
	 Esp_audio: 'common/audio/words/esp/188.mp3',
 	 img:       'common/images/words/188.png'
 	},
	{id:        189,
	 Eng_name:  'Gum',
	 Eng_audio: 'common/audio/words/eng/189.mp3',
	 Por_name:  'Chiclete',
	 Por_audio: 'common/audio/words/por/189.mp3',
	 Esp_name:  'Chicle',
	 Esp_audio: 'common/audio/words/esp/189.mp3',
 	 img:       'common/images/words/189.png'
 	},
	// {id:        190,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/190.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/190.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/190.mp3',
 // 	 img:       'common/images/words/190.png'
 // 	},
	// {id:        191,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/191.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/191.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/191.mp3',
 // 	 img:       'common/images/words/191.png'
 // 	},
	// {id:        192,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/192.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/192.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/192.mp3',
 // 	 img:       'common/images/words/192.png'
 // 	},
	// {id:        193,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/193.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/193.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/193.mp3',
 // 	 img:       'common/images/words/193.png'
 // 	},
	// {id:        194,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/194.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/194.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/194.mp3',
 // 	 img:       'common/images/words/194.png'
 // 	},
	// {id:        195,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/195.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/195.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/195.mp3',
 // 	 img:       'common/images/words/195.png'
 // 	},
	// {id:        196,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/196.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/196.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/196.mp3',
 // 	 img:       'common/images/words/196.png'
 // 	},
	// {id:        197,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/197.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/197.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/197.mp3',
 // 	 img:       'common/images/words/197.png'
 // 	},
	// {id:        198,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/198.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/198.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/198.mp3',
 // 	 img:       'common/images/words/198.png'
 // 	},
	// {id:        199,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/199.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/199.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/199.mp3',
 // 	 img:       'common/images/words/199.png'
 // 	},
	// {id:        200,
	//  Eng_name:  '',
	//  Eng_audio: 'common/audio/words/eng/200.mp3',
	//  Por_name:  '',
	//  Por_audio: 'common/audio/words/por/200.mp3',
	//  Esp_name:  '',
	//  Esp_audio: 'common/audio/words/esp/200.mp3',
 // 	 img:       'common/images/words/200.png'}
]);