<!DOCTYPE html>
<html ng-app>
<head>
    <meta charset="utf-8">
    <title>Talk | Pioneers</title>
    <meta name="description" contect="EDIT:PURPOSE OF THIS WEBPAGE">
    <meta name="author" content="Nathan Birch">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="/home/css/primary.css" rel="stylesheet" type="text/css" media="screen">
    <link href="/home/css/bootstrap.css" rel="stylesheet" type="text/css" media="screen">
    <!-- favicon --><link href="data:image/x-icon;base64,AAABAAEAEBACAAAAAACwAAAAFgAAACgAAAAQAAAAIAAAAAEAAQAAAAAAQAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAPv/AAAAAAADwAAAD/AAABw4AAA73AAAN+wAAHfuAAB//gAAeZ4AAHmeAAA//AAAP/wAAB/4AAAP8AAAA8AAAAAAAAD8PwAA8A8AAOAHAADAAwAAgAEAAIABAAAAAAAAAAAAAAAAAAAAAAAAgAEAAIABAADAAwAA4AcAAPAPAAD8PwAA" rel="icon" type="image/x-icon" />
</head>
<body>
 <!-- Include the header.php file for the top navigation bar -->
 <header role="banner">
  <div>
  <?php include $_SERVER['DOCUMENT_ROOT']. '/home/modules/header.php';  ?>  
  </div>
 </header>
  <!-- BREADCRUMBS -->
  <div class="dumb container">
   <ol style="padding-top:13px" class="crumb">
       <a class="crumbP" href="/"><u>Home</u></a> >> 
       <a class="crumbP" href="/home/pages/myTalks.php"><u>My Talks</u></a> >> <b class="crumbC">Pioneers</b>
   </ol>
  </div>
  <!-- END BREADCRUMBS -->
 <main class="container">
   <h1>Talk on Pioneers</h1> 
    <h3>Talk Given on July 24th, 2016</h3>
    <div style="padding-left:30px; padding-right:30px">
        <p>Well, I kind of want to grab Sarah’s talk and read it to ya’ll again.  I loved it.  But, I’m excited to share mine with you as well. As I have prepared this talk, I have felt motivation to change and better my own life and I’m excited to share some of my thoughts on these things that I’ve learned.  I pray that the Spirit will be here to teach each of us, and that we may be open and accepting to His teachings.</p>
        <p>Throughout my talk today, I wish to share several stories of pioneer experiences.  It is my hope, that each one of these stories will help us to better understand our own journey through this life, and how we can be successful in navigating it. </p>
        <p class="quote">Eliza R. Snow was a pioneer that had an interesting first night on the trek.  She said that on the first evening of their journey, nine children were born.  I can’t even imagine having a baby the first night away from civilization...or leaving civilization knowing my wife’s due date is coming up.  But these nine kiddos that were born that first night, were just a small number of the many children that were born during journeys across the plains.  Zina D.H. Young, gave birth in the back of a covered wagon. She halted the march of the company when it happened. Though the birthing conditions were far from ideal, these mothers carried on. Zina said that “I did not mind the hardship of my situation, for my life had been preserved, and my babe seemed so beautiful.” (Ensign article “Courage—The Unfailing Beacon”).</p>
        <p>These simple stories about delivering children during this journey caused me to ponder much on the faith of these women, and many other pioneers in similar situations.  How much courage and faith must they and their husbands of had to be able to embark on this journey and continue each day?  Of course it would have been physically trying, but I’m sure that the emotional weight at times seemed too much to bear.  The faith of these people is inspiring to us today.  It reminds me of a scripture found in Proverbs. It reads:</p>
        <p class="quote">1 My son, forget not my law; but let thine heart keep my commandments:</p>
        <p class="quote">5 Trust in the Lord with all thine heart; and lean not unto thine own understanding.</p>
        <p class="quote">6 In all thy ways acknowledge him, and he shall direct thy paths.  (Proverbs 3)</p>
        <p>These pioneers knew the value of keeping the commandments of God.  For despite their exceeding trials, they were able to find peace through the atonement of Jesus Christ.  This peace is a result of faithfully following the example of Jesus Christ and is a promised blessing to those who follow him in faith.  I think of the way these pioneer women chose to embark on this journey knowing they were about to give birth. And if that wasn’t a large enough trial of their faith…nine of them gave birth that first night.  It would not surprise me if there were moments when individuals would say to themselves, “holy cow…if this is happening on the first night, what is going to happen over the coming months? ...maybe we should stop while we’re ahead.”  But, whether they realized it or not at the time…opposition is one of our greatest blessings in this life.</p>
        <p>As I ponder on my own life and on the experiences that I have both had and witnessed, I realize that life has a lot of challenges, and plenty of opposition for all.  From the Book of Mormon, it was Lehi who taught his children,</p>
        <p class="quote">11 For it must needs be, that there is an opposition in all things. If not so, righteousness could not be brought to pass, neither wickedness, neither holiness nor misery, neither good nor bad.</p>
        <p>And so it is with us: no opposition means no trial, no growth, no purpose, and even somewhat meaningless choices in life.  Opposition is a blessing because when faced with faith in the Lord, Jesus Christ, it is what builds our character and brings us unto Him. It is what helps us to experience joy in this life and value the things that we have.  These pioneers suffered much, and experienced much opposition. Their stories of faith in spite of opposition, inspire all who hear them.  May we remember the example of these mothers<strong>: to be strong in the face of opposition</strong>.</p>
        <p> </p>
        <p>My next story is of a woman named Susanna Stone. </p>
        <p class="quote">“I joined the Church of Jesus Christ of Latter Day Saints about the year 1848. This caused my heart to rejoice. I have seen that the hand of the Lord has been over me for good from my earliest childhood and I know that his Holy Spirit has been my constant guide and companion. I never shall forget the many manifestations of the Lord's goodness and blessings unto me and mine.”</p>
        <p>Susannah Stone was the only member of her family to join the Church. At the age of 25, despite the protests of family and friends, she left to go to America and joined the Willie Handcart company. She says that “only once did my courage fail.” It was at a time when she was alone and her feet had become frosted over and she stopped and “sat down to await the end.”  She then recounts,</p>
        <p class="quote">“After a time I was aroused by a voice, which seemed as audible as anything could be, and which spoke to my very soul of the promises and blessings I had received and that I had a mission to perform in Zion. I received strength, and was filled with the Spirit of the Lord and arose and traveled on with a light heart.”</p>
        <p>When she reached camp, Susannah found a search party ready to go look for her. She continued on the trek, and the day she reached the valley was also the day she met her future husband, Thomas Lloyd. Susannah would have 14 children, and become Relief Society secretary.</p>
        <p>In the brief moment that we’ve learned about Susanna just now, there are many things about her and her character that would be good for us to emulate in our own lives.  I wish to emphasize the way in which she chose to be strong in the face of opposition.  She was ready to die and thought that she was going to.  When the Spirit spoke to her, <u>she chose</u> to get up and carry on.  She mentioned that her courage failed…but apparently it was only for a moment.  What helped her in this time of need was the Lord and the enabling power of the atonement.  Elder Bednar, in teaching about the atonement and how it can be used in our lives said the following,</p>
        <p class="quote">“I frankly do not think many of us ‘get it’ concerning [the] enabling and strengthening aspect of the Atonement, and I wonder if we mistakenly believe we must make the journey from good to better and become a saint all by ourselves through sheer grit, willpower, and discipline, and with our obviously limited capacities.”</p>
        <p>He then taught,</p>
        <p class="quote">“In the Bible Dictionary we learn that the word grace frequently is used in the scriptures to connote a strengthening or enabling power:</p>
        <p class="quote">“The main idea of the word is divine means of help or strength, given through the bounteous mercy and love of Jesus Christ.</p>
        <p class="quote">“… It is likewise through the grace of the Lord that individuals, through faith in the atonement of Jesus Christ and repentance of their sins, receive strength and assistance to do good works that they otherwise would not be able to maintain if left to their own means. This grace is an enabling power that allows men and women to lay hold on eternal life and exaltation after they have expended their own best efforts” (p. 697).</p>
        <p class="quote">Thus, the enabling and strengthening aspect of the Atonement helps us to see and to do and to become good in ways that we could never recognize or accomplish with our limited mortal capacity. I testify and witness that the enabling power of the Savior’s Atonement is real. Without that strengthening power of the Atonement, I could not stand before you this morning.</p>
        <p>Can we see this in the story of Susannah Stone?  She was about to die. She didn’t have any more strength to continue on…but through the atonement, she did.  There were two things that happened that allowed her to survive, and eventually make it to Zion and bear 14 children. </p>
        <ul>
        <li>First: the Lord helped to strengthen her through the power of the Atonement.</li>
        <li>Second: she chose to get up and keep going.</li>
        </ul>
        <p>Had either one of these not been present in that moment, she would have died there.  So it is in our lives.  Our lives are made up of moments. And moments boil down to decisions.  If we choose to follow the Savior in faith, then we will come to know a similar peace and joy that the pioneers experienced when reaching their destination.  The Lord is always reaching out to us. He knows what we are feeling. He knows what we’re struggling with.  He knows our deepest desires and our most dreaded fears. </p>
        <p>There are many instances throughout the scriptures, particularly in Isaiah, where we learn of a people messing up big time, and then we see the words, “For all this his anger is not turned away, but his hand is stretched out still.”  I am continually humbled by the greatness and mercy of God.  I am continually humbled by His love for me, and the fact that His hand is always stretched out towards me. </p>
        <p>In the home that I grew up in, we have a large painting of the Savior.  In it, there is a beautiful river full of large rocks and white water. Towards the bottom of the picture, there is a little girl stretching on her toes reaching upward with one hand, while her other is propped on a higher rock.  Above her, is the Savior, holding a small boy with his left arm, and reaching down with his right hand, managing to reach her and seems to be pulling her up to him.  Like her, sometimes we find ourselves in perilous situations.  Whether it is just the difficulties of life, or whether we made some mistakes that put us there…it doesn’t matter, the Lord’s hand is always extended to us.  May we learn from the example of Susannah Stone: to <strong>choose to take the Lord’s hand, to get up and to keep going</strong>.</p>
        <p> </p>
        <p>The third story that I would like to mention, was shared by Sarah.  I would like to share just the last piece of it:</p>
        <p class="quote">“Three eighteen-year-old boys belonging to the relief party came to the rescue, and to the astonishment of all who saw, carried nearly every member of the ill-fated handcart company across the snowbound stream. The strain was so terrible, and the exposure so great, that in later years all the boys died from the effects of it. When President Brigham Young heard of this heroic act, he wept like a child, and later declared publicly, ‘that act alone will ensure C. Allen Huntington, George W. Grant, and David P. Kimball an everlasting salvation in the Celestial Kingdom of God, worlds without end.’” (Solomon F. Kimball, Improvement Era, Feb. 1914, p. 288.)</p>
        <p>Each time I hear this story, I wonder what the people felt when they saw that they would be able to continue their journey, because of the goodness of these young men.  I wonder what kinds of things they said to the young men before getting picked up, and after making it across the river.  But I also wonder what these three young men felt as they provided this incredibly selfless and loving service to this group of people. </p>
        <p>I imagine that it was a similar feeling to that of a missionary leaving their home for some time to go serve the Lord, or individuals in daily life who selflessly give to others because of their Christ-like love.  Mormon taught that, “every thing which inviteth to do good, and to persuade to believe in Christ, is sent forth by the power and gift of Christ (Moroni 7:16).”  As we choose to take hold of every good thing, we will become children of Christ.  His Spirit will be with us always, not only to influence how we feel and how we act.  But it will also purify us, and bring about a continual change in us that will bring us closer and closer to the Savior of the world.  I believe that these three young men had done their best to follow the example of their Savior.  I believe that because of their acts of faith long before this moment in time, they were prepared in that moment to love these people as Christ did, and to give their lives for them as Christ did. </p>
        <p>Brothers and sisters, the purpose of life is not only to receive a body and be tested.  The purpose of this life is to prepare to meet God.  We do this by making covenants with our Heavenly Father, and being faithful to those covenants through the rest of our lives.  This will bring about the change that I mentioned a moment ago, of becoming children of Christ, of becoming pure as He is, of becoming more and more like He is.  Jesus Christ commanded, “Therefore I would that ye should be perfect even as I, or your Father who is in heaven is perfect. (3 Nephi 12:48).”  This happens through choosing to act in faith in the simple moments that make up a lifetime.  So any time there is a simple moment in life that presents a bit of opposition, know that if you choose the right, you are taking a step towards God. You are training yourself to be obedient to His word even when it is hard, or seemingly unimportant; you are showing Him that you want and are worthy of His Spirit.  May we learn from these three boys that <strong>following in the footsteps of the Savior, will ultimately lead us to Him and will enable us to return to His presence and receive the greatest of all the gifts of God: Eternal Life.</strong></p>
        <p> </p>
        <p>Each one of these stories actually happened.  They happened here, in this land, not very long ago.  Remembering these and other stories like them can help us live the gospel of Jesus Christ.  As I studied for this talk, I felt powerful impressions while reading through many pioneer stories, and I could feel the Spirit of God testifying to me of truth.  I think one of the reasons why they are so powerful to us is because in a way, we are pioneers.  Elder Oaks asked the prompting question, “Do you, like the pioneers, have the courage and the consistency to be true to the faith and endure to the end? (Oct. 1997 – Following the Pioneers).”  END QUOTE!!!</p>
        <p>Thankfully, we do not have to push handcarts across a country.  But the spiritual equivalent to all the wickedness we face in the world, is like pulling a handcart up Mount Everest…with all of our modern appliances in it.  We live in a very wicked world.  In a book Elder Maxwell wrote called <u>Notwithstanding My Weakness</u>, he taught,</p>
        <p class="quote">“Though we have rightly applauded our ancestors for their spiritual achievements (and do not and must not discount them now), those of us who prevail today will have done no small thing. The special spirits who have been reserved to live in this time of challenges and who overcome will one day be praised for their stamina by those who pulled handcarts. (18)”</p>
        <p>So any time we are overcome with burdens and feel like we are in the bitter winters some of the pioneers faced, let us remember these principles from these stories.</p>
        <ol>
        <li>From the example of the mothers – <strong>Let us be strong in opposition.</strong></li>
        <li>From the example Susannah Stone - <strong>Choose to take the Lord’s hand, to get up and to keep going. He will always provide a way for us to succeed.</strong></li>
        <li>From the story of C. Allen Huntington, George W. Grant, and David P. Kimball - <strong>Following in the footsteps of the Savior, will ultimately lead us to Him.</strong></li>
        </ol>
        <p>I know that these principles are true.  I know because I have felt the joy and peace that come through living them in my own life.  I am very far from where I want to be, but I am continually reminded by a loving Heavenly Father of who He wants me to be, and who…with His help, I can become.  It is not easy to stay strong in the midst of opposition or temptation.  But…it is worth it.  It is possible.  With the Lord, anything is possible.  His hand is always extended to us. We would be wise to reach for it, and hold onto it for dear life.  With the wickedness of the world increasing every day, we need our Savior as our lifeline. He is the only way by which we can know peace in this world, and eternal happiness throughout the eternities.  I love my Savior.  I love my Heavenly Father.  I want to be the best I can so that I can live with them again, and so that I can live with my precious family forever.  In the name of Jesus Christ, amen.</p>
    </div>
   
 </main>
 <footer role="contentinfo">
 <!-- Include the footer.php file for the top navigation bar -->
  <div>
  <?php include $_SERVER['DOCUMENT_ROOT']. '/home/modules/footer.php';  ?>
  </div>
 <!-- display on the website when this page was updated last -->
    
 </footer>
</body>
</html>