var toggleCompletion = function(itemNumber) {
    itemNumber.status = itemNumber.status === false ? true : false;
    if (itemNumber.status === true) {
        $scope.itemChecked = true;
    }
    else {
        $scope.itemChecked = false;
    }
};
function loadText(){

    var jsExercisesArray = 
           {"exerciseArray": [
               {"icon"      : "c.png",
                "number"    : "1.",
                "link"      : "http://www.asmarterwaytolearn.com/js/1.html",
                "linkTitle": "Alerts"},
               {"icon"      : "c.png",
                "number"    : "2.",
                "link"      : "http://www.asmarterwaytolearn.com/js/2.html",
                "linkTitle": "Variables for Strings"},
               {"icon"      : "c.png",
                "number"    : "3.",
                "link"      : "http://www.asmarterwaytolearn.com/js/3.html",
                "linkTitle": "Variables for Numbers"},
               {"icon"      : "c.png",
                "number"    : "4.",
                "link"      : "http://www.asmarterwaytolearn.com/js/4.html",
                "linkTitle": "Variable Names Legal and Illegal"},
               {"icon"      : "c.png",
                "number"    : "5.",
                "link"      : "http://www.asmarterwaytolearn.com/js/5.html",
                "linkTitle": "Math Expressions:  familiar operators"},
               {"icon"      : "c.png",
                "number"    : "6.",
                "link"      : "http://www.asmarterwaytolearn.com/js/6.html",
                "linkTitle": "Math Expressions: unfamiliar operators"},
               {"icon"      : "c.png",
                "number"    : "7.",
                "link"      : "http://www.asmarterwaytolearn.com/js/7.html",
                "linkTitle": "Math Expressions: eliminating ambiguity"},
               {"icon"      : "c.png",
                "number"    : "8.",
                "link"      : "http://www.asmarterwaytolearn.com/js/8.html",
                "linkTitle": "Concatenating text strings"},
               {"icon"      : "c.png",
                "number"    : "9.",
                "link"      : "http://www.asmarterwaytolearn.com/js/9.html",
                "linkTitle": "Prompts"},
               {"icon"      : "g.png",
                "number"    : "10.",
                "link"      : "http://www.asmarterwaytolearn.com/js/10.html",
                "linkTitle": "<em>if</em> statements"},
               {"icon"      : "g.png",
                "number"    : "11.",
                "link"      : "http://www.asmarterwaytolearn.com/js/11.html",
                "linkTitle": "Comparison operators"},
               {"icon"      : "g.png",
                "number"    : "12.",
                "link"      : "http://www.asmarterwaytolearn.com/js/12.html",
                "linkTitle": "<em>if...else</em> and <em>else if </em>statements"},
               {"icon"      : "g.png",
                "number"    : "13.",
                "link"      : "http://www.asmarterwaytolearn.com/js/13.html",
                "linkTitle": "Testing sets of conditions"},
               {"icon"      : "g.png",
                "number"    : "14.",
                "link"      : "http://www.asmarterwaytolearn.com/js/14.html",
                "linkTitle": "<em>if</em> statements nested"},
               {"icon"      : "g.png",
                "number"    : "15.",
                "link"      : "http://www.asmarterwaytolearn.com/js/15.html",
                "linkTitle": "Arrays"},
               {"icon"      : "g.png",
                "number"    : "16.",
                "link"      : "http://www.asmarterwaytolearn.com/js/16.html",
                "linkTitle": "Arrays: adding and removing elements"},
               {"icon"      : "g.png",
                "number"    : "17.",
                "link"      : "http://www.asmarterwaytolearn.com/js/17.html",
                "linkTitle": "Arrays: removing, inserting, and extracting elements"},
               {"icon"      : "g.png",
                "number"    : "18.",
                "link"      : "http://www.asmarterwaytolearn.com/js/18.html",
                "linkTitle": "<em>for</em> loops"},
               {"icon"      : "g.png",
                "number"    : "19.",
                "link"      : "http://www.asmarterwaytolearn.com/js/19.html",
                "linkTitle": "<em>for </em>loops: flags, Booleans, array length, and loopus interruptus"},
               {"icon"      : "g.png",
                "number"    : "20.",
                "link"      : "http://www.asmarterwaytolearn.com/js/20.html",
                "linkTitle": "<em>for</em> loops nested"},
               {"icon"      : "g.png",
                "number"    : "21.",
                "link"      : "http://www.asmarterwaytolearn.com/js/21.html",
                "linkTitle": "Changing case"},
               {"icon"      : "g.png",
                "number"    : "22.",
                "link"      : "http://www.asmarterwaytolearn.com/js/22.html",
                "linkTitle": "Strings: measuring length and extracting parts"},
               {"icon"      : "g.png",
                "number"    : "23.",
                "link"      : "http://www.asmarterwaytolearn.com/js/23.html",
                "linkTitle": "Strings: finding segments"},
               {"icon"      : "g.png",
                "number"    : "24.",
                "link"      : "http://www.asmarterwaytolearn.com/js/24.html",
                "linkTitle": "Strings: finding a character at a location"},
               {"icon"      : "g.png",
                "number"    : "25.",
                "link"      : "http://www.asmarterwaytolearn.com/js/25.html",
                "linkTitle": "Strings: replacing characters"},
               {"icon"      : "g.png",
                "number"    : "26.",
                "link"      : "http://www.asmarterwaytolearn.com/js/26.html",
                "linkTitle": "Rounding numbers"},
               {"icon"      : "g.png",
                "number"    : "27.",
                "link"      : "http://www.asmarterwaytolearn.com/js/27.html",
                "linkTitle": "Generating random numbers"},
               {"icon"      : "g.png",
                "number"    : "28.",
                "link"      : "http://www.asmarterwaytolearn.com/js/28.html",
                "linkTitle": "Converting strings to integers and decimals"},
               {"icon"      : "g.png",
                "number"    : "29.",
                "link"      : "http://www.asmarterwaytolearn.com/js/29.html",
                "linkTitle": "Converting strings to numbers,  numbers to strings"},
               {"icon"      : "g.png",
                "number"    : "30.",
                "link"      : "http://www.asmarterwaytolearn.com/js/30.html",
                "linkTitle": "Controlling the length of decimals"},
               {"icon"      : "g.png",
                "number"    : "31.",
                "link"      : "http://www.asmarterwaytolearn.com/js/31.html",
                "linkTitle": "Getting the current date and time"},
               {"icon"      : "g.png",
                "number"    : "32.",
                "link"      : "http://www.asmarterwaytolearn.com/js/32.html",
                "linkTitle": "Extracting parts of the date and time"},
               {"icon"      : "g.png",
                "number"    : "33.",
                "link"      : "http://www.asmarterwaytolearn.com/js/33.html",
                "linkTitle": "Specifying a date and time"},
               {"icon"      : "g.png",
                "number"    : "34.",
                "link"      : "http://www.asmarterwaytolearn.com/js/34.html",
                "linkTitle": "Changing elements of a date and time"},
               {"icon"      : "g.png",
                "number"    : "35.",
                "link"      : "http://www.asmarterwaytolearn.com/js/35.html",
                "linkTitle": "Functions"},
               {"icon"      : "g.png",
                "number"    : "36.",
                "link"      : "http://www.asmarterwaytolearn.com/js/36.html",
                "linkTitle": "Functions: passing them data"},
               {"icon"      : "g.png",
                "number"    : "37.",
                "link"      : "http://www.asmarterwaytolearn.com/js/37.html",
                "linkTitle": "Functions: passing data back from them"},
               {"icon"      : "g.png",
                "number"    : "38.",
                "link"      : "http://www.asmarterwaytolearn.com/js/38.html",
                "linkTitle": "Functions: local vs. global variables"},
               {"icon"      : "g.png",
                "number"    : "39.",
                "link"      : "http://www.asmarterwaytolearn.com/js/39.html",
                "linkTitle": "<em>switch</em> statements: how to start them"},
               {"icon"      : "g.png",
                "number"    : "40.",
                "link"      : "http://www.asmarterwaytolearn.com/js/40.html",
                "linkTitle": "<em>switch</em> statements: how to complete them"},
               {"icon"      : "g.png",
                "number"    : "41.",
                "link"      : "http://www.asmarterwaytolearn.com/js/41.html",
                "linkTitle": "<em>while</em> loops"},
               {"icon"      : "g.png",
                "number"    : "42.",
                "link"      : "http://www.asmarterwaytolearn.com/js/42.html",
                "linkTitle": "<em>do...while</em> loops"},
               {"icon"      : "g.png",
                "number"    : "43.",
                "link"      : "http://www.asmarterwaytolearn.com/js/43.html",
                "linkTitle": "Placing scripts"},
               {"icon"      : "g.png",
                "number"    : "44.",
                "link"      : "http://www.asmarterwaytolearn.com/js/44.html",
                "linkTitle": "Commenting"},
               {"icon"      : "g.png",
                "number"    : "45.",
                "link"      : "http://www.asmarterwaytolearn.com/js/45.html",
                "linkTitle": "Events: link"},
               {"icon"      : "g.png",
                "number"    : "46.",
                "link"      : "http://www.asmarterwaytolearn.com/js/46.html",
                "linkTitle": "Events: button"},
               {"icon"      : "g.png",
                "number"    : "47.",
                "link"      : "http://www.asmarterwaytolearn.com/js/47.html",
                "linkTitle": "Events: mouse"},
               {"icon"      : "g.png",
                "number"    : "48.",
                "link"      : "http://www.asmarterwaytolearn.com/js/48.html",
                "linkTitle": "Events: fields "},
               {"icon"      : "g.png",
                "number"    : "49.",
                "link"      : "http://www.asmarterwaytolearn.com/js/49.html",
                "linkTitle": "Reading field values"},
               {"icon"      : "g.png",
                "number"    : "50.",
                "link"      : "http://www.asmarterwaytolearn.com/js/50.html",
                "linkTitle": "Setting field values"},
               {"icon"      : "g.png",
                "number"    : "51.",
                "link"      : "http://www.asmarterwaytolearn.com/js/51.html",
                "linkTitle": "Reading and setting paragraph text"},
               {"icon"      : "g.png",
                "number"    : "52.",
                "link"      : "http://www.asmarterwaytolearn.com/js/52.html",
                "linkTitle": "Manipulating images and text"},
               {"icon"      : "g.png",
                "number"    : "53.",
                "link"      : "http://www.asmarterwaytolearn.com/js/53.html",
                "linkTitle": "Swapping images"},
               {"icon"      : "g.png",
                "number"    : "54.",
                "link"      : "http://www.asmarterwaytolearn.com/js/54.html",
                "linkTitle": "Swapping images and setting classes"},
               {"icon"      : "g.png",
                "number"    : "55.",
                "link"      : "http://www.asmarterwaytolearn.com/js/55.html",
                "linkTitle": "Setting styles"},
               {"icon"      : "g.png",
                "number"    : "56.",
                "link"      : "http://www.asmarterwaytolearn.com/js/56.html",
                "linkTitle": "Target all elements by tag name"},
               {"icon"      : "g.png",
                "number"    : "57.",
                "link"      : "http://www.asmarterwaytolearn.com/js/57.html",
                "linkTitle": "Target some elements by tag name"},
               {"icon"      : "g.png",
                "number"    : "58.",
                "link"      : "http://www.asmarterwaytolearn.com/js/58.html",
                "linkTitle": "The DOM"},
               {"icon"      : "g.png",
                "number"    : "59.",
                "link"      : "http://www.asmarterwaytolearn.com/js/59.html",
                "linkTitle": "The DOM: Parents and children"},
               {"icon"      : "g.png",
                "number"    : "60.",
                "link"      : "http://www.asmarterwaytolearn.com/js/60.html",
                "linkTitle": "The DOM: Finding children"},
               {"icon"      : "g.png",
                "number"    : "61.",
                "link"      : "http://www.asmarterwaytolearn.com/js/61.html",
                "linkTitle": "The DOM: Junk artifacts and nodeType"},
               {"icon"      : "g.png",
                "number"    : "62.",
                "link"      : "http://www.asmarterwaytolearn.com/js/62.html",
                "linkTitle": "The DOM: More ways to target elements"},
               {"icon"      : "g.png",
                "number"    : "63.",
                "link"      : "http://www.asmarterwaytolearn.com/js/63.html",
                "linkTitle": "The DOM: Getting a target's name"},
               {"icon"      : "g.png",
                "number"    : "64.",
                "link"      : "http://www.asmarterwaytolearn.com/js/64.html",
                "linkTitle": "The DOM: Counting elements"},
               {"icon"      : "g.png",
                "number"    : "65.",
                "link"      : "http://www.asmarterwaytolearn.com/js/65.html",
                "linkTitle": "The DOM: Attributes"},
               {"icon"      : "g.png",
                "number"    : "66.",
                "link"      : "http://www.asmarterwaytolearn.com/js/66.html",
                "linkTitle": "The DOM: Attribute names and values"},
               {"icon"      : "g.png",
                "number"    : "67.",
                "link"      : "http://www.asmarterwaytolearn.com/js/67.html",
                "linkTitle": "The DOM: Adding nodes"},
               {"icon"      : "g.png",
                "number"    : "68.",
                "link"      : "http://www.asmarterwaytolearn.com/js/68.html",
                "linkTitle": "The DOM: Inserting nodes"},
               {"icon"      : "g.png",
                "number"    : "69.",
                "link"      : "http://www.asmarterwaytolearn.com/js/69.html",
                "linkTitle": "Objects"},
               {"icon"      : "g.png",
                "number"    : "70.",
                "link"      : "http://www.asmarterwaytolearn.com/js/70.html",
                "linkTitle": "Objects: Properties"},
               {"icon"      : "g.png",
                "number"    : "71.",
                "link"      : "http://www.asmarterwaytolearn.com/js/71.html",
                "linkTitle": "Objects: Methods"},
               {"icon"      : "g.png",
                "number"    : "72.",
                "link"      : "http://www.asmarterwaytolearn.com/js/72.html",
                "linkTitle": "Objects: Constructors"},
               {"icon"      : "g.png",
                "number"    : "73.",
                "link"      : "http://www.asmarterwaytolearn.com/js/73.html",
                "linkTitle": "Objects: Constructors for methods"},
               {"icon"      : "g.png",
                "number"    : "74.",
                "link"      : "http://www.asmarterwaytolearn.com/js/74.html",
                "linkTitle": "Objects: Prototypes"},
               {"icon"      : "g.png",
                "number"    : "75.",
                "link"      : "http://www.asmarterwaytolearn.com/js/75.html",
                "linkTitle": "Objects: Checking for properties and methods"},
               {"icon"      : "g.png",
                "number"    : "76.",
                "link"      : "http://www.asmarterwaytolearn.com/js/76.html",
                "linkTitle": "Browser control: Getting and setting the URL"},
               {"icon"      : "g.png",
                "number"    : "77.",
                "link"      : "http://www.asmarterwaytolearn.com/js/77.html",
                "linkTitle": "Browser control: Getting and setting the URL another way"},
               {"icon"      : "g.png",
                "number"    : "78.",
                "link"      : "http://www.asmarterwaytolearn.com/js/78.html",
                "linkTitle": "Browser control: Forward and reverse"},
               {"icon"      : "g.png",
                "number"    : "79.",
                "link"      : "http://www.asmarterwaytolearn.com/js/79.html",
                "linkTitle": "Browser control: Filling the window with content"},
               {"icon"      : "g.png",
                "number"    : "80.",
                "link"      : "http://www.asmarterwaytolearn.com/js/80.html",
                "linkTitle": "Browser control: Controlling the window's size and location"},
               {"icon"      : "g.png",
                "number"    : "81.",
                "link"      : "http://www.asmarterwaytolearn.com/js/81.html",
                "linkTitle": "Browser control: Testing for popup blockers"},
               {"icon"      : "g.png",
                "number"    : "82.",
                "link"      : "http://www.asmarterwaytolearn.com/js/82.html",
                "linkTitle": "Form validation:  text fields"},
               {"icon"      : "g.png",
                "number"    : "83.",
                "link"      : "http://www.asmarterwaytolearn.com/js/83.html",
                "linkTitle": "Form validation:  drop-downs"},
               {"icon"      : "g.png",
                "number"    : "84.",
                "link"      : "http://www.asmarterwaytolearn.com/js/84.html",
                "linkTitle": "Form validation:  radio buttons"},
               {"icon"      : "g.png",
                "number"    : "85.",
                "link"      : "http://www.asmarterwaytolearn.com/js/85.html",
                "linkTitle": "Form validation: ZIP codes"},
               {"icon"      : "g.png",
                "number"    : "86.",
                "link"      : "http://www.asmarterwaytolearn.com/js/86.html",
                "linkTitle": "Form validation: email"},
               {"icon"      : "g.png",
                "number"    : "87.",
                "link"      : "http://www.asmarterwaytolearn.com/js/87.html",
                "linkTitle": "Exceptions: try and catch"},
               {"icon"      : "g.png",
                "number"    : "88.",
                "link"      : "http://www.asmarterwaytolearn.com/js/88.html",
                "linkTitle": "Exceptions: throw"},
               {"icon"      : "g.png",
                "number"    : "89.",
                "link"      : "http://www.asmarterwaytolearn.com/js/89.html",
                "linkTitle": "Handle events within JavaScript"}       
        ]
    };
    for (i = 0; i < jsExercisesArray.exerciseArray.length; i++) { 
        
        var myIcon  = jsExercisesArray.exerciseArray[i].icon;
        var myNum   = jsExercisesArray.exerciseArray[i].number;
        var myLink  = jsExercisesArray.exerciseArray[i].link;
        var myLinkT = jsExercisesArray.exerciseArray[i].linkTitle;
        
        var demop = document.getElementById('printArray');
        
        demop.innerHTML += "<img src='" + myIcon + "' id='c'> " + 
                          myNum + " " + "<a href='" + 
                          myLink + "' target='_blank'>" + 
                          myLinkT + "</a><br>";
    }
}
  
loadText();    
    
    
    
    
    
    
    
//        var i = 0;   	// Change this to any number between 0 and 2 to see a different student displayed
//
//        var my_JSON_Text = '{"students" : [{"first_name":"Jonny","last_name":"Job","major":"Software Engineering"},{"first_name":"Brittany","last_name":"Stone","major":"Computer Information Technology"},{"first_name":"Laura","last_name":"Watson","major":"Computer Science"}]}';
//        var my_JS_Object = JSON.parse(my_JSON_Text);
//
//        document.getElementById("printArray").innerHTML = "Name: " +
//                my_JS_Object.students[i].first_name + " " +
//                my_JS_Object.students[i].last_name + "<br> Major: " +
//                my_JS_Object.students[i].major+ "<br>";