gospelApp.constant("ages", [
	// {title:             'Ages',
	//  relatedQuotesStr:  '',
	//  relatedTalks:      [],
	//  relatedTopics:     [],
	//  displayImage:      'constants/img/a0.png',
	//  description:       '',
	//  id:                0,
	//  },
	{title:             '0-6 Months',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a1.png',
	 description:       '',
	 id:                1,
	 },
	{title:             '7-12 Months',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a2.png',
	 description:       '',
	 id:                2,
	 },
	{title:             '1 Year',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a3.png',
	 description:       '',
	 id:                3,
	 },
	{title:             '2 Years',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a4.png',
	 description:       '',
	 id:                4,
	 },
	{title:             '3 Years',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a5.png',
	 description:       '',
	 id:                5,
	 },
	{title:             '4-7 Years',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a6.png',
	 description:       '',
	 id:                6,
	 },
	{title:             '8-11 Years',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a7.png',
	 description:       '',
	 id:                7,
	 },
	{title:             '12-15 Years',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a8.png',
	 description:       '',
	 id:                8,
	 },
	{title:             '16-18 Years',
	 relatedQuotesStr:  '',
	 relatedTalks:      [],
	 relatedTopics:     [],
	 displayImage:      'constants/img/a9.png',
	 description:       '',
	 id:                9,
	 }
]);