gospelApp.constant("people", [
	{name:  'dummy',
 	 url:   'dummy',
 	 img:   'dummy',
 	 id:    0},
	{name:  'Alvin R. Dyer',
 	 url:   'https://en.wikipedia.org/wiki/Alvin_R._Dyer',
 	 img:   'constants/img/people/1.png',
 	 id:    1},
	{name:  'Bonnie D. Parkin',
 	 url:   'https://www.lds.org/callings/relief-society/relief-society-presidents/bonnie-d-parkin?lang=eng',
 	 img:   'constants/img/people/2.png',
 	 id:    2},
	{name:  'Brigham Young',
 	 url:   'https://history.lds.org/article/brigham-young-video-downloads?lang=eng',
 	 img:   'constants/img/people/3.png',
 	 id:    3},
	{name:  'Bruce R. McConkie',
 	 url:   'https://www.lds.org/new-era/1985/06/in-memoriam-elder-bruce-r-mcconkie-advocate-for-truth?lang=eng',
 	 img:   'constants/img/people/4.png',
 	 id:    4},
	{name:  'Dallin H. Oaks',
 	 url:   'https://www.lds.org/church/leader/dallin-h-oaks?lang=eng',
 	 img:   'constants/img/people/5.png',
 	 id:    5},
	{name:  'David R. Stone',
 	 url:   'https://www.lds.org/ensign/1999/05/news-of-the-church/elder-david-r-stone-of-the-seventy?lang=eng',
 	 img:   'constants/img/people/6.png',
 	 id:    6},
	{name:  'Ezra Taft Benson',
 	 url:   'https://history.lds.org/article/ezra-taft-benson-video-downloads?lang=eng',
 	 img:   'constants/img/people/7.png',
 	 id:    7},
	{name:  'George Albert Smith',
 	 url:   'https://en.wikipedia.org/wiki/George_Albert_Smith',
 	 img:   'constants/img/people/8.png',
 	 id:    8},
	{name:  'George Q. Cannon',
 	 url:   'https://en.wikipedia.org/wiki/George_Q._Cannon',
 	 img:   'constants/img/people/9.png',
 	 id:    9},
	{name:  'Gordon B. Hinckley',
 	 url:   'http://www.gordonbhinckley.org/',
 	 img:   'constants/img/people/10.png',
 	 id:    10},
	{name:  'Harold B. Lee',
 	 url:   'https://en.wikipedia.org/wiki/Harold_B._Lee',
 	 img:   'constants/img/people/11.png',
 	 id:    11},
	{name:  'Heber C. Kimball ',
 	 url:   'https://en.wikipedia.org/wiki/Heber_C._Kimball',
 	 img:   'constants/img/people/12.png',
 	 id:    12},
	{name:  'Howard W. Hunter',
 	 url:   'https://www.lds.org/manual/presidents-of-the-church-teacher-manual-religion-345/howard-w-hunter-fourteenth-president-of-the-church?lang=eng',
 	 img:   'constants/img/people/13.png',
 	 id:    13},
	{name:  'James E. Faust',
 	 url:   'https://en.wikipedia.org/wiki/James_E._Faust',
 	 img:   'constants/img/people/14.png',
 	 id:    14},
	{name:  'Jeffrey R. Holland',
 	 url:   'https://www.lds.org/church/leader/jeffrey-r-holland?lang=eng',
 	 img:   'constants/img/people/15.png',
 	 id:    15},
	{name:  'John Taylor',
 	 url:   'https://en.wikipedia.org/wiki/John_Taylor_(Mormon)',
 	 img:   'constants/img/people/16.png',
 	 id:    16},
	{name:  'Joseph B. Wirthlin ',
 	 url:   'https://en.wikipedia.org/wiki/Joseph_B._Wirthlin',
 	 img:   'constants/img/people/17.png',
 	 id:    17},
	{name:  'Joseph Fielding Smith',
 	 url:   'https://en.wikipedia.org/wiki/Joseph_Fielding_Smith',
 	 img:   'constants/img/people/18.png',
 	 id:    18},
	{name:  'Joseph Smith',
 	 url:   'https://www.lds.org/topics/joseph-smith?lang=eng',
 	 img:   'constants/img/people/19.png',
 	 id:    19},
	{name:  'Leland H. Gentry (CES Teacher)',
 	 url:   '',
 	 img:   '',
 	 id:    20},
	{name:  'Melvin J. Ballard',
 	 url:   'https://en.wikipedia.org/wiki/Melvin_J._Ballard',
 	 img:   'constants/img/people/21.png',
 	 id:    21},
	{name:  'Neal A. Maxwell',
 	 url:   'https://en.wikipedia.org/wiki/Neal_A._Maxwell',
 	 img:   'constants/img/people/22.png',
 	 id:    22},
	{name:  'Quentin L. Cook',
 	 url:   'https://www.lds.org/church/leader/quentin-l-cook?lang=eng',
 	 img:   'constants/img/people/23.png',
 	 id:    23},
	{name:  'Rafael E. Pino',
 	 url:   'https://www.lds.org/church/leader/rafael-e-pino?lang=eng',
 	 img:   'constants/img/people/24.png',
 	 id:    24},
	{name:  'Richard G. Scott',
 	 url:   'https://www.lds.org/church/leader/richard-g-scott?lang=eng',
 	 img:   'constants/img/people/25.png',
 	 id:    25},
	{name:  'Robert J. Matthews (Professor, BYU)',
 	 url:   'https://en.wikipedia.org/wiki/Robert_J._Matthews',
 	 img:   'constants/img/people/26.png',
 	 id:    26},
	{name:  'Spencer J. Condie',
 	 url:   'https://en.wikipedia.org/wiki/Spencer_J._Condie',
 	 img:   'constants/img/people/27.png',
 	 id:    27},
	{name:  'Spencer W. Kimball',
 	 url:   'https://www.lds.org/manual/presidents-of-the-church-teacher-manual-religion-345/spencer-w-kimball-twelfth-president-of-the-church?lang=eng',
 	 img:   'constants/img/people/28.png',
 	 id:    28},
	{name:  'Thomas Pain ',
 	 url:   'https://en.wikipedia.org/wiki/Thomas_Paine',
 	 img:   'constants/img/people/29.png',
 	 id:    29},
	{name:  'Thomas S. Monson',
 	 url:   'https://www.lds.org/church/leader/thomas-s-monson?lang=eng',
 	 img:   'constants/img/people/30.png',
 	 id:    30},
	{name:  'Wilford Woodruff',
 	 url:   'https://www.lds.org/manual/presidents-of-the-church-teacher-manual-religion-345/wilford-woodruff-fourth-president-of-the-church?lang=eng',
 	 img:   'constants/img/people/31.png',
 	 id:    31},
	{name:  'Lorenzo Snow',
 	 url:   'https://www.lds.org/media-library/video/lorenzo-snow?lang=eng',
 	 img:   'constants/img/people/32.png',
 	 id:    32},
	{name:  'Orson Pratt',
 	 url:   'https://en.wikipedia.org/wiki/Orson_Pratt',
 	 img:   'constants/img/people/33.png',
 	 id:    33},
	{name:  'William Ross Wallace',
 	 url:   'https://en.wikipedia.org/wiki/William_Ross_Wallace',
 	 img:   'constants/img/people/34.png',
 	 id:    34},
	{name:  'David O. McKay',
 	 url:   'https://www.lds.org/manual/teachings-david-o-mckay/the-life-and-ministry-of-david-o-mckay?lang=eng',
 	 img:   'constants/img/people/35.png',
 	 id:    35},
	{name:  'Robert D. Hales',
 	 url:   'https://www.lds.org/prophets-and-apostles/what-are-prophets/bio/robert-d-hales?lang=eng',
 	 img:   'constants/img/people/36.png',
 	 id:    36},
	{name:  'N. Eldon Tanner',
 	 url:   'https://www.lds.org/ensign/1983/01/president-n-eldon-tanner-dies?lang=eng',
 	 img:   'constants/img/people/37.png',
 	 id:    37},
	{name:  'L. Tom Perry',
 	 url:   'https://www.lds.org/prophets-and-apostles/biographies/elder-l-tom-perry?lang=eng',
 	 img:   'constants/img/people/38.png',
 	 id:    38},
	{name:  'Hugh B. Brown',
 	 url:   'https://www.lds.org/ensign/1976/01/elder-hugh-b-brown-18831975-in-memoriam?lang=eng',
 	 img:   'constants/img/people/39.png',
 	 id:    39},
	{name:  'Joseph F. Smith',
 	 url:   'https://www.lds.org/manual/teachings-joseph-f-smith/the-ministry-of-joseph-f-smith?lang=eng',
 	 img:   'constants/img/people/40.png',
 	 id:    40},
	{name:  'Orson F. Whitney',
 	 url:   'https://en.wikipedia.org/wiki/Orson_F._Whitney',
 	 img:   'constants/img/people/41.png',
 	 id:    41},
	{name:  'Theodore M. Burton',
 	 url:   'https://www.lds.org/ensign/1990/03/news-of-the-church/elder-theodore-m-burton-dies?lang=eng',
 	 img:   'constants/img/people/42.png',
 	 id:    42},
	{name:  'James E. Talmage',
 	 url:   'https://en.wikipedia.org/wiki/James_E._Talmage',
 	 img:   'constants/img/people/43.png',
 	 id:    43},
	{name:  'Henry B. Eyring',
 	 url:   'https://www.lds.org/church/leader/henry-b-eyring?lang=eng',
 	 img:   'constants/img/people/44.png',
 	 id:    44},
	{name:  'Marion G. Romney',
 	 url:   'https://www.lds.org/ensign/1986/04/president-marion-g-romney-president-of-the-quorum-of-the-twelve-apostles?lang=eng',
 	 img:   'constants/img/people/45.png',
 	 id:    45},
	{name:  'Parley P. Pratt',
 	 url:   'https://www.lds.org/ensign/2007/04/the-extraordinary-life-of-parley-p-pratt?lang=eng',
 	 img:   'constants/img/people/46.png',
 	 id:    46},
	{name:  'Boyd K. Packer',
 	 url:   'https://www.lds.org/church/leader/boyd-k-packer?lang=eng',
 	 img:   'constants/img/people/47.png',
 	 id:    47},
	{name:  'Franklin D. Richards',
 	 url:   'https://www.lds.org/ensign/1988/01/news-of-the-church/elder-franklin-d-richards-eulogized?lang=eng',
 	 img:   'constants/img/people/48.png',
 	 id:    48},
	{name:  'Hyrum M. Smith',
 	 url:   'https://en.wikipedia.org/wiki/Hyrum_M._Smith',
 	 img:   'constants/img/people/49.png',
 	 id:    49},
	{name:  'Charles W. Penrose',
 	 url:   'https://en.wikipedia.org/wiki/Charles_W._Penrose',
 	 img:   'constants/img/people/50.png',
 	 id:    50},
	{name:  'LeGrand Richards',
 	 url:   'https://www.lds.org/ensign/1983/02/elder-legrand-richards-dies-beloved-apostle-missionary-friend?lang=eng',
 	 img:   'constants/img/people/51.png',
 	 id:    51},
	{name:  'John A. Widtsoe',
 	 url:   'https://www.lds.org/liahona/2010/02/small-and-simple-things/elder-john-a-widtsoe?lang=eng',
 	 img:   'constants/img/people/52.png',
 	 id:    52},
	{name:  'D. Todd Christofferson',
 	 url:   'https://www.lds.org/church/leader/d-todd-christofferson?lang=eng',
 	 img:   'constants/img/people/53.png',
 	 id:    53},
	{name:  'Russell M. Nelson',
 	 url:   'https://www.lds.org/church/leader/russell-m-nelson?lang=eng',
 	 img:   'constants/img/people/54.png',
 	 id:    54},
	{name:  'M. Russell Ballard',
 	 url:   'https://www.lds.org/church/leader/m-russell-ballard?lang=eng',
 	 img:   'constants/img/people/55.png',
 	 id:    55},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/56.png',
 // 	 id:    56},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/57.png',
 // 	 id:    57},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/58.png',
 // 	 id:    58},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/59.png',
 // 	 id:    59},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/60.png',
 // 	 id:    60},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/61.png',
 // 	 id:    61},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/62.png',
 // 	 id:    62},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/63.png',
 // 	 id:    63},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/64.png',
 // 	 id:    64},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/65.png',
 // 	 id:    65},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/66.png',
 // 	 id:    66},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/67.png',
 // 	 id:    67},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/68.png',
 // 	 id:    68},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/69.png',
 // 	 id:    69},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/70.png',
 // 	 id:    70},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/71.png',
 // 	 id:    71},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/72.png',
 // 	 id:    72},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/73.png',
 // 	 id:    73},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/74.png',
 // 	 id:    74},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/75.png',
 // 	 id:    75},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/76.png',
 // 	 id:    76},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/77.png',
 // 	 id:    77},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/78.png',
 // 	 id:    78},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/79.png',
 // 	 id:    79},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/80.png',
 // 	 id:    80},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/81.png',
 // 	 id:    81},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/82.png',
 // 	 id:    82},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/83.png',
 // 	 id:    83},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/84.png',
 // 	 id:    84},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/85.png',
 // 	 id:    85},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/86.png',
 // 	 id:    86},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/87.png',
 // 	 id:    87},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/88.png',
 // 	 id:    88},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/89.png',
 // 	 id:    89},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/90.png',
 // 	 id:    90},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/91.png',
 // 	 id:    91},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/92.png',
 // 	 id:    92},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/93.png',
 // 	 id:    93},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/94.png',
 // 	 id:    94},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/95.png',
 // 	 id:    95},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/96.png',
 // 	 id:    96},
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/97.png',
 // 	 id:    97}
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/98.png',
 // 	 id:    98}
	// {name:  '',
 // 	 url:   '',
 // 	 img:   'constants/img/people/99.png',
 // 	 id:    99}
	{name:  '',
 	 url:   '',
 	 img:   'constants/img/people/100.png',
 	 id:    100}
]);